/* ========================================
   musicLibrary.js - 1000+ Curated Songs
   ======================================== */

export const GENRES = [
  { id: 'all', name: 'All', icon: '🎵' },
  { id: 'hiphop', name: 'Hip Hop', icon: '🎤' },
  { id: 'pop', name: 'Pop', icon: '⭐' },
  { id: 'rnb', name: 'R&B', icon: '💜' },
  { id: 'rock', name: 'Rock', icon: '🎸' },
  { id: 'electronic', name: 'Electronic', icon: '🎧' },
  { id: 'latin', name: 'Latin', icon: '🌴' },
  { id: 'country', name: 'Country', icon: '🤠' },
  { id: 'indie', name: 'Indie', icon: '🌻' },
  { id: 'kpop', name: 'K-Pop', icon: '🇰🇷' },
  { id: 'metal', name: 'Metal', icon: '🤘' },
  { id: 'reggae', name: 'Reggae', icon: '🇯🇲' },
  { id: 'afrobeats', name: 'Afrobeats', icon: '🌍' },
  { id: 'classic', name: 'Classics', icon: '📻' },
  { id: 'soul', name: 'Soul/Funk', icon: '🎷' },
  { id: 'punk', name: 'Punk', icon: '⚡' },
  { id: 'jazz', name: 'Jazz', icon: '🎺' },
  { id: 'classical', name: 'Classical', icon: '🎻' },
  { id: 'anime', name: 'Anime', icon: '🎌' },
  { id: 'worship', name: 'Worship', icon: '✝️' },
];

export const SONGS = [
  // ===================== HIP HOP (180+) =====================
  // Drake
  { id: 'hh1', title: "God's Plan", artist: 'Drake', ytId: 'xpVfcZ0ZcFM', genre: 'hiphop' },
  { id: 'hh2', title: 'Hotline Bling', artist: 'Drake', ytId: 'uxpDa-c-4Mc', genre: 'hiphop' },
  { id: 'hh3', title: 'One Dance', artist: 'Drake ft. Wizkid', ytId: 'iAbnEUA0wpA', genre: 'hiphop' },
  { id: 'hh4', title: 'In My Feelings', artist: 'Drake', ytId: 'DRS_PpOrUZ4', genre: 'hiphop' },
  { id: 'hh5', title: 'Started From The Bottom', artist: 'Drake', ytId: 'RubBzkZzpUA', genre: 'hiphop' },
  { id: 'hh6', title: 'Nice For What', artist: 'Drake', ytId: 'U9BwWKXjVaI', genre: 'hiphop' },
  { id: 'hh7', title: 'Nonstop', artist: 'Drake', ytId: '6XjDE4Iu5ww', genre: 'hiphop' },
  { id: 'hh8', title: 'Passionfruit', artist: 'Drake', ytId: 'COz9lDCFHjw', genre: 'hiphop' },
  { id: 'hh9', title: 'Headlines', artist: 'Drake', ytId: 'cimoNqiulUE', genre: 'hiphop' },
  { id: 'hh10', title: 'Hold On Were Going Home', artist: 'Drake', ytId: 'GxgqpCdOKak', genre: 'hiphop' },
  { id: 'hh11', title: 'Take Care', artist: 'Drake ft. Rihanna', ytId: '-zzP29emgpg', genre: 'hiphop' },
  { id: 'hh12', title: 'Best I Ever Had', artist: 'Drake', ytId: 'SoqYruD84fk', genre: 'hiphop' },
  { id: 'hh13', title: 'Laugh Now Cry Later', artist: 'Drake ft. Lil Durk', ytId: 'JFm7YDVlqnI', genre: 'hiphop' },
  { id: 'hh14', title: 'Toosie Slide', artist: 'Drake', ytId: 'xWggTb45brM', genre: 'hiphop' },
  { id: 'hh15', title: 'Controlla', artist: 'Drake', ytId: 'Sdj2yGwDm54', genre: 'hiphop' },
  { id: 'hh16', title: 'Fake Love', artist: 'Drake', ytId: 'ZhQIOMgxFqA', genre: 'hiphop' },
  { id: 'hh17', title: 'Forever', artist: 'Drake, Kanye, Lil Wayne, Eminem', ytId: 'eDuRoPIOBjE', genre: 'hiphop' },
  // Travis Scott
  { id: 'hh20', title: 'SICKO MODE', artist: 'Travis Scott', ytId: '6ONRf7h3Mdk', genre: 'hiphop' },
  { id: 'hh21', title: 'Goosebumps', artist: 'Travis Scott ft. Kendrick', ytId: 'Dst9gZkq1a8', genre: 'hiphop' },
  { id: 'hh22', title: 'Highest In The Room', artist: 'Travis Scott', ytId: 'tfSS1e3kYeo', genre: 'hiphop' },
  { id: 'hh23', title: 'Antidote', artist: 'Travis Scott', ytId: 'KnZ8h3MRuYg', genre: 'hiphop' },
  { id: 'hh24', title: 'Butterfly Effect', artist: 'Travis Scott', ytId: '_EyZUTDAH0U', genre: 'hiphop' },
  { id: 'hh25', title: 'STARGAZING', artist: 'Travis Scott', ytId: '2a8PgqWrc_4', genre: 'hiphop' },
  { id: 'hh26', title: 'Pick Up The Phone', artist: 'Travis Scott & Young Thug', ytId: 'mZDinQ92OZQ', genre: 'hiphop' },
  { id: 'hh27', title: 'FRANCHISE', artist: 'Travis Scott ft. Young Thug', ytId: 'nkpYbJ2PvFU', genre: 'hiphop' },
  { id: 'hh28', title: '90210', artist: 'Travis Scott', ytId: 'BuNBLjJzRoo', genre: 'hiphop' },
  { id: 'hh29', title: 'ASTROWORLD', artist: 'Travis Scott', ytId: 'DP4_bTqDPW4', genre: 'hiphop' },
  { id: 'hh30', title: 'FE!N', artist: 'Travis Scott ft. Playboi Carti', ytId: 'bVfVxmXN2XA', genre: 'hiphop' },
  // Kendrick Lamar
  { id: 'hh35', title: 'HUMBLE', artist: 'Kendrick Lamar', ytId: 'tvTRZJ-4EyI', genre: 'hiphop' },
  { id: 'hh36', title: 'Money Trees', artist: 'Kendrick Lamar', ytId: 'smqhSl0u_sI', genre: 'hiphop' },
  { id: 'hh37', title: 'DNA', artist: 'Kendrick Lamar', ytId: 'NLZRYQMLDW4', genre: 'hiphop' },
  { id: 'hh38', title: 'Swimming Pools', artist: 'Kendrick Lamar', ytId: '8-ejyHzz3XE', genre: 'hiphop' },
  { id: 'hh39', title: 'Alright', artist: 'Kendrick Lamar', ytId: 'Z-48u_uWMHY', genre: 'hiphop' },
  { id: 'hh40', title: 'King Kunta', artist: 'Kendrick Lamar', ytId: 'hRK7PVJFbS8', genre: 'hiphop' },
  { id: 'hh41', title: 'Backseat Freestyle', artist: 'Kendrick Lamar', ytId: 'EZW7et3tPuQ', genre: 'hiphop' },
  { id: 'hh42', title: 'LOYALTY', artist: 'Kendrick Lamar ft. Rihanna', ytId: 'Dlh-dzB2U4Y', genre: 'hiphop' },
  { id: 'hh43', title: 'Not Like Us', artist: 'Kendrick Lamar', ytId: 'T6eK-2OQtew', genre: 'hiphop' },
  { id: 'hh44', title: 'Poetic Justice', artist: 'Kendrick Lamar ft. Drake', ytId: 'yyr2gEouEMM', genre: 'hiphop' },
  { id: 'hh45', title: 'Bitch Dont Kill My Vibe', artist: 'Kendrick Lamar', ytId: 'GF8aaTu2kg0', genre: 'hiphop' },
  // Post Malone
  { id: 'hh50', title: 'Rockstar', artist: 'Post Malone ft. 21 Savage', ytId: 'UceaB4D0jpo', genre: 'hiphop' },
  { id: 'hh51', title: 'Congratulations', artist: 'Post Malone ft. Quavo', ytId: 'SC4xMk98Pdc', genre: 'hiphop' },
  { id: 'hh52', title: 'White Iverson', artist: 'Post Malone', ytId: 'SLsTskih7_I', genre: 'hiphop' },
  { id: 'hh53', title: 'Circles', artist: 'Post Malone', ytId: 'wXhTHyIgQ_U', genre: 'hiphop' },
  { id: 'hh54', title: 'Sunflower', artist: 'Post Malone & Swae Lee', ytId: 'ApXoWvfEYVU', genre: 'hiphop' },
  { id: 'hh55', title: 'Better Now', artist: 'Post Malone', ytId: 'UYwF-jdcVjY', genre: 'hiphop' },
  { id: 'hh56', title: 'Psycho', artist: 'Post Malone ft. Ty Dolla Sign', ytId: 'au2n7VVGv_c', genre: 'hiphop' },
  { id: 'hh57', title: 'I Fall Apart', artist: 'Post Malone', ytId: 'sc5iTNVEOAg', genre: 'hiphop' },
  { id: 'hh58', title: 'Wow', artist: 'Post Malone', ytId: '393C3pr2ioY', genre: 'hiphop' },
  { id: 'hh59', title: 'Goodbyes', artist: 'Post Malone ft. Young Thug', ytId: 'ba7mB8oueCY', genre: 'hiphop' },
  { id: 'hh60', title: 'Candy Paint', artist: 'Post Malone', ytId: 'K-bSSsjmhVg', genre: 'hiphop' },
  // Juice WRLD
  { id: 'hh65', title: 'Lucid Dreams', artist: 'Juice WRLD', ytId: 'mzB1VGEGcSU', genre: 'hiphop' },
  { id: 'hh66', title: 'Robbery', artist: 'Juice WRLD', ytId: 'iI34LYmJ1Fs', genre: 'hiphop' },
  { id: 'hh67', title: 'All Girls Are The Same', artist: 'Juice WRLD', ytId: 'h3EJICKwITw', genre: 'hiphop' },
  { id: 'hh68', title: 'Bandit', artist: 'Juice WRLD & NBA YoungBoy', ytId: 'Zc3cxj5pDIs', genre: 'hiphop' },
  { id: 'hh69', title: 'Wishing Well', artist: 'Juice WRLD', ytId: 'C4rYMJohnCo', genre: 'hiphop' },
  { id: 'hh70', title: 'Lean Wit Me', artist: 'Juice WRLD', ytId: '5SejM_hBvMM', genre: 'hiphop' },
  { id: 'hh71', title: 'Righteous', artist: 'Juice WRLD', ytId: 'g9Tgpc4jkEA', genre: 'hiphop' },
  { id: 'hh72', title: 'Come & Go', artist: 'Juice WRLD & Marshmello', ytId: 'mVCC0MBT6bE', genre: 'hiphop' },
  { id: 'hh73', title: 'Legends', artist: 'Juice WRLD', ytId: 'tsuFQLUsBg0', genre: 'hiphop' },
  { id: 'hh74', title: 'Empty', artist: 'Juice WRLD', ytId: 'lRXuwfn7gQY', genre: 'hiphop' },
  // Lil Uzi Vert
  { id: 'hh80', title: 'XO Tour Llif3', artist: 'Lil Uzi Vert', ytId: 'WrsFXgQk5UI', genre: 'hiphop' },
  { id: 'hh81', title: 'Money Longer', artist: 'Lil Uzi Vert', ytId: '1eoLzHi2MhA', genre: 'hiphop' },
  { id: 'hh82', title: 'The Way Life Goes', artist: 'Lil Uzi Vert', ytId: 'Vi2XaiKhgiU', genre: 'hiphop' },
  { id: 'hh83', title: '20 Min', artist: 'Lil Uzi Vert', ytId: 'ByTNJdOcXvY', genre: 'hiphop' },
  { id: 'hh84', title: 'Futsal Shuffle 2020', artist: 'Lil Uzi Vert', ytId: 'g1K_RQLDZ7c', genre: 'hiphop' },
  { id: 'hh85', title: 'Just Wanna Rock', artist: 'Lil Uzi Vert', ytId: 'YP-nKia5SQ4', genre: 'hiphop' },
  { id: 'hh86', title: 'New Patek', artist: 'Lil Uzi Vert', ytId: 'bSCP3pSB8p0', genre: 'hiphop' },
  // Eminem
  { id: 'hh90', title: 'Lose Yourself', artist: 'Eminem', ytId: '_Yhyp-_hX2s', genre: 'hiphop' },
  { id: 'hh91', title: 'Not Afraid', artist: 'Eminem', ytId: 'j5-yKhDd64s', genre: 'hiphop' },
  { id: 'hh92', title: 'Love The Way You Lie', artist: 'Eminem ft. Rihanna', ytId: 'uelHwf8o7_U', genre: 'hiphop' },
  { id: 'hh93', title: 'The Real Slim Shady', artist: 'Eminem', ytId: 'eJO5HU_7_1w', genre: 'hiphop' },
  { id: 'hh94', title: 'Without Me', artist: 'Eminem', ytId: 'YVkUvmDQ3HY', genre: 'hiphop' },
  { id: 'hh95', title: 'Stan', artist: 'Eminem ft. Dido', ytId: 'gOMhN-hfMtY', genre: 'hiphop' },
  { id: 'hh96', title: 'Mockingbird', artist: 'Eminem', ytId: 'S9bCLPwzSC0', genre: 'hiphop' },
  { id: 'hh97', title: 'Rap God', artist: 'Eminem', ytId: 'XbGs_qK2PQA', genre: 'hiphop' },
  { id: 'hh98', title: 'Godzilla', artist: 'Eminem ft. Juice WRLD', ytId: 'r_0JjYUe5jo', genre: 'hiphop' },
  { id: 'hh99', title: 'The Monster', artist: 'Eminem ft. Rihanna', ytId: 'EHkozMIXZ8w', genre: 'hiphop' },
  { id: 'hh100', title: 'Sing For The Moment', artist: 'Eminem', ytId: 'D4hAVemuQXY', genre: 'hiphop' },
  { id: 'hh101', title: 'Cleanin Out My Closet', artist: 'Eminem', ytId: 'RQ9_TKayu9s', genre: 'hiphop' },
  // Kanye West
  { id: 'hh105', title: 'Stronger', artist: 'Kanye West', ytId: 'PsO6ZnUZI0g', genre: 'hiphop' },
  { id: 'hh106', title: 'Gold Digger', artist: 'Kanye West ft. Jamie Foxx', ytId: '6vwNcNOTVzY', genre: 'hiphop' },
  { id: 'hh107', title: 'Heartless', artist: 'Kanye West', ytId: 'Co0tTeuUVhU', genre: 'hiphop' },
  { id: 'hh108', title: 'All Of The Lights', artist: 'Kanye West', ytId: 'HAfFfqiYLp0', genre: 'hiphop' },
  { id: 'hh109', title: 'Flashing Lights', artist: 'Kanye West', ytId: 'ila-hAUXR5U', genre: 'hiphop' },
  { id: 'hh110', title: 'Power', artist: 'Kanye West', ytId: 'L53gjP-TtGE', genre: 'hiphop' },
  { id: 'hh111', title: 'Runaway', artist: 'Kanye West', ytId: 'Bm5iA4Zupek', genre: 'hiphop' },
  { id: 'hh112', title: 'Father Stretch My Hands', artist: 'Kanye West', ytId: 'wuO4_P_8p-Q', genre: 'hiphop' },
  { id: 'hh113', title: 'Touch The Sky', artist: 'Kanye West', ytId: 'Ce7j9aVStwQ', genre: 'hiphop' },
  { id: 'hh114', title: 'Jesus Walks', artist: 'Kanye West', ytId: 'MYF7H_fpc-g', genre: 'hiphop' },
  // Jay-Z
  { id: 'hh120', title: 'Empire State of Mind', artist: 'Jay-Z ft. Alicia Keys', ytId: '0UjsXo9l6I8', genre: 'hiphop' },
  { id: 'hh121', title: '99 Problems', artist: 'Jay-Z', ytId: 'WwoM5fLITfk', genre: 'hiphop' },
  { id: 'hh122', title: 'Run This Town', artist: 'Jay-Z ft. Rihanna & Kanye', ytId: 'xcIvILFM6Lc', genre: 'hiphop' },
  { id: 'hh123', title: 'Dirt Off Your Shoulder', artist: 'Jay-Z', ytId: 'Oz_-VaTHpc8', genre: 'hiphop' },
  { id: 'hh124', title: 'Izzo (H.O.V.A)', artist: 'Jay-Z', ytId: 'x3VZ0jJvPiU', genre: 'hiphop' },
  // More Hip Hop
  { id: 'hh130', title: 'Bad and Boujee', artist: 'Migos ft. Lil Uzi Vert', ytId: 'S-sJp1FfG7Q', genre: 'hiphop' },
  { id: 'hh131', title: 'Motorsport', artist: 'Migos ft. Nicki Minaj & Cardi B', ytId: 'FD20-bq83oQ', genre: 'hiphop' },
  { id: 'hh132', title: 'Stir Fry', artist: 'Migos', ytId: 'oCveByMXd_0', genre: 'hiphop' },
  { id: 'hh133', title: 'Walk It Talk It', artist: 'Migos ft. Drake', ytId: 'fGqdIPer-ms', genre: 'hiphop' },
  { id: 'hh134', title: 'T-Shirt', artist: 'Migos', ytId: 'dKSNe8F9wYo', genre: 'hiphop' },
  { id: 'hh135', title: 'Bodak Yellow', artist: 'Cardi B', ytId: 'PEGccV-NOm8', genre: 'hiphop' },
  { id: 'hh136', title: 'I Like It', artist: 'Cardi B ft. Bad Bunny & J Balvin', ytId: 'xTlNMmZKwpA', genre: 'hiphop' },
  { id: 'hh137', title: 'WAP', artist: 'Cardi B ft. Megan Thee Stallion', ytId: 'hsm4poTWjMs', genre: 'hiphop' },
  { id: 'hh138', title: 'Money', artist: 'Cardi B', ytId: 'zUOh09GOyBE', genre: 'hiphop' },
  { id: 'hh139', title: 'Press', artist: 'Cardi B', ytId: 'UjyVy4S7Tfg', genre: 'hiphop' },
  { id: 'hh140', title: 'Super Bass', artist: 'Nicki Minaj', ytId: '4JipHEz53sU', genre: 'hiphop' },
  { id: 'hh141', title: 'Anaconda', artist: 'Nicki Minaj', ytId: 'LDZX4ooRsWs', genre: 'hiphop' },
  { id: 'hh142', title: 'Starships', artist: 'Nicki Minaj', ytId: 'SeIJmciN8mo', genre: 'hiphop' },
  { id: 'hh143', title: 'Bang Bang', artist: 'Jessie J, Ariana Grande, Nicki Minaj', ytId: '0HDdjwpPM3Y', genre: 'hiphop' },
  { id: 'hh144', title: 'Savage', artist: 'Megan Thee Stallion', ytId: 'qeCpD5bVtFA', genre: 'hiphop' },
  { id: 'hh145', title: 'Hot Girl Summer', artist: 'Megan Thee Stallion', ytId: 'ldaMC4cZqFo', genre: 'hiphop' },
  { id: 'hh146', title: 'Body', artist: 'Megan Thee Stallion', ytId: 'MEJrFycMNzE', genre: 'hiphop' },
  { id: 'hh147', title: 'Mo Bamba', artist: 'Sheck Wes', ytId: 'VWoIpDVkOH0', genre: 'hiphop' },
  { id: 'hh148', title: 'Panda', artist: 'Desiigner', ytId: 'E5ONTXHS2mM', genre: 'hiphop' },
  { id: 'hh149', title: 'Mask Off', artist: 'Future', ytId: 'xvZqHgFz51I', genre: 'hiphop' },
  { id: 'hh150', title: 'March Madness', artist: 'Future', ytId: '6SU5K1yFlS4', genre: 'hiphop' },
  { id: 'hh151', title: 'Life Is Good', artist: 'Future ft. Drake', ytId: 'l0U7SxXHkPY', genre: 'hiphop' },
  { id: 'hh152', title: 'Low Life', artist: 'Future ft. The Weeknd', ytId: 'K_9tX4eHztY', genre: 'hiphop' },
  { id: 'hh153', title: 'Drip Too Hard', artist: 'Lil Baby & Gunna', ytId: 'THCNheGcNAU', genre: 'hiphop' },
  { id: 'hh154', title: 'Yes Indeed', artist: 'Lil Baby & Drake', ytId: 'bv7tS_lN8LQ', genre: 'hiphop' },
  { id: 'hh155', title: 'Woah', artist: 'Lil Baby', ytId: 'k8u6SEJHYl4', genre: 'hiphop' },
  { id: 'hh156', title: 'The Bigger Picture', artist: 'Lil Baby', ytId: '_VDGysJGNoI', genre: 'hiphop' },
  { id: 'hh157', title: 'A Lot', artist: '21 Savage ft. J. Cole', ytId: 'DmWWqogr_r8', genre: 'hiphop' },
  { id: 'hh158', title: 'Bank Account', artist: '21 Savage', ytId: 'I8Je9gCL7cw', genre: 'hiphop' },
  { id: 'hh159', title: 'Tunnel Vision', artist: 'Kodak Black', ytId: 'Tz6OUIjtM6E', genre: 'hiphop' },
  { id: 'hh160', title: 'Family Ties', artist: 'Baby Keem & Kendrick Lamar', ytId: 'v7EjGRH2_MM', genre: 'hiphop' },
  { id: 'hh161', title: 'Orange Soda', artist: 'Baby Keem', ytId: 'o3P6Gn0vVbM', genre: 'hiphop' },
  { id: 'hh162', title: 'Whats Poppin', artist: 'Jack Harlow', ytId: 'HIwAI05Y1fU', genre: 'hiphop' },
  { id: 'hh163', title: 'First Class', artist: 'Jack Harlow', ytId: 'TF-rl8AEF5I', genre: 'hiphop' },
  { id: 'hh164', title: 'Industry Baby', artist: 'Lil Nas X ft. Jack Harlow', ytId: 'UTHLKHL_whs', genre: 'hiphop' },
  { id: 'hh165', title: 'Old Town Road', artist: 'Lil Nas X ft. Billy Ray Cyrus', ytId: 'w2Ov5jzm3j8', genre: 'hiphop' },
  { id: 'hh166', title: 'MONTERO', artist: 'Lil Nas X', ytId: '6swmTBVI83k', genre: 'hiphop' },
  { id: 'hh167', title: 'Hotline Hotline', artist: 'Billie Eilish & Justin Bieber', ytId: 'k2qgadSvNyU', genre: 'hiphop' },
  { id: 'hh168', title: 'Lifestyle', artist: 'Rich Gang ft. Young Thug', ytId: 'nGt_JGHYEO4', genre: 'hiphop' },
  { id: 'hh169', title: 'Pick Up The Phone', artist: 'Young Thug', ytId: 'mZDinQ92OZQ', genre: 'hiphop' },
  { id: 'hh170', title: 'Go Crazy', artist: 'Chris Brown & Young Thug', ytId: '0xJFWs5evUI', genre: 'hiphop' },
  { id: 'hh171', title: 'Ric Flair Drip', artist: 'Offset & Metro Boomin', ytId: 'LPTlvQ1Zet0', genre: 'hiphop' },
  { id: 'hh172', title: 'Ballin', artist: 'Mustard ft. Roddy Ricch', ytId: 'w1PlqM-RNxQ', genre: 'hiphop' },
  { id: 'hh173', title: 'The Box', artist: 'Roddy Ricch', ytId: 'uLHqpjW3aDs', genre: 'hiphop' },
  { id: 'hh174', title: 'High Fashion', artist: 'Roddy Ricch ft. Mustard', ytId: 'ydE24T4K_LY', genre: 'hiphop' },
  { id: 'hh175', title: 'Lemonade', artist: 'Internet Money ft. Gunna', ytId: 'Ir6clMJOrxA', genre: 'hiphop' },
  { id: 'hh176', title: 'Mood', artist: '24kGoldn ft. iann dior', ytId: 'GrAchTdepsU', genre: 'hiphop' },
  { id: 'hh177', title: 'Rockstar', artist: 'DaBaby ft. Roddy Ricch', ytId: 'mxFstYSbBmc', genre: 'hiphop' },
  { id: 'hh178', title: 'Suge', artist: 'DaBaby', ytId: 'kQ7TceWWuuE', genre: 'hiphop' },
  { id: 'hh179', title: 'Bop', artist: 'DaBaby', ytId: '28hYUZMufDg', genre: 'hiphop' },
  { id: 'hh180', title: 'Levitating Remix', artist: 'Dua Lipa ft. DaBaby', ytId: 'WHuBW3qKm9g', genre: 'hiphop' },

  // ===================== POP (180+) =====================
  // Taylor Swift
  { id: 'pop1', title: 'Anti-Hero', artist: 'Taylor Swift', ytId: 'b1kbLwvqugk', genre: 'pop' },
  { id: 'pop2', title: 'Shake It Off', artist: 'Taylor Swift', ytId: 'nfWlot6h_JM', genre: 'pop' },
  { id: 'pop3', title: 'Blank Space', artist: 'Taylor Swift', ytId: 'e-ORhEE9VVg', genre: 'pop' },
  { id: 'pop4', title: 'Love Story', artist: 'Taylor Swift', ytId: '8xg3vE8Ie_E', genre: 'pop' },
  { id: 'pop5', title: 'You Belong With Me', artist: 'Taylor Swift', ytId: 'VuNIsY6JdUw', genre: 'pop' },
  { id: 'pop6', title: 'Bad Blood', artist: 'Taylor Swift ft. Kendrick Lamar', ytId: 'QcIy9NiNbmo', genre: 'pop' },
  { id: 'pop7', title: 'Look What You Made Me Do', artist: 'Taylor Swift', ytId: '3tmd-ClpJxA', genre: 'pop' },
  { id: 'pop8', title: 'We Are Never Getting Back Together', artist: 'Taylor Swift', ytId: 'WA4iX5D9Z64', genre: 'pop' },
  { id: 'pop9', title: 'Delicate', artist: 'Taylor Swift', ytId: 'tCXGJQYZ9JA', genre: 'pop' },
  { id: 'pop10', title: 'Cruel Summer', artist: 'Taylor Swift', ytId: 'ic8j13piAhQ', genre: 'pop' },
  { id: 'pop11', title: 'Cardigan', artist: 'Taylor Swift', ytId: 'K-a8s8OLBSE', genre: 'pop' },
  { id: 'pop12', title: 'Willow', artist: 'Taylor Swift', ytId: 'RsEZmictANA', genre: 'pop' },
  { id: 'pop13', title: 'All Too Well', artist: 'Taylor Swift', ytId: 'tollGa3S0o8', genre: 'pop' },
  { id: 'pop14', title: '22', artist: 'Taylor Swift', ytId: 'AgFeZr5ptV8', genre: 'pop' },
  { id: 'pop15', title: 'Style', artist: 'Taylor Swift', ytId: '-CmadmM5cOk', genre: 'pop' },
  { id: 'pop16', title: 'I Knew You Were Trouble', artist: 'Taylor Swift', ytId: 'vNoKguSdy4Y', genre: 'pop' },
  { id: 'pop17', title: 'Wildest Dreams', artist: 'Taylor Swift', ytId: 'IdneKLhsWOQ', genre: 'pop' },
  { id: 'pop18', title: 'ME!', artist: 'Taylor Swift ft. Brendon Urie', ytId: 'FuXNumBwDOM', genre: 'pop' },
  // Ed Sheeran
  { id: 'pop20', title: 'Shape of You', artist: 'Ed Sheeran', ytId: 'JGwWNGJdvx8', genre: 'pop' },
  { id: 'pop21', title: 'Perfect', artist: 'Ed Sheeran', ytId: '2Vv-BfVoq4g', genre: 'pop' },
  { id: 'pop22', title: 'Thinking Out Loud', artist: 'Ed Sheeran', ytId: 'lp-EO5I60KA', genre: 'pop' },
  { id: 'pop23', title: 'Photograph', artist: 'Ed Sheeran', ytId: 'nSDgHBxUbVQ', genre: 'pop' },
  { id: 'pop24', title: 'Castle on the Hill', artist: 'Ed Sheeran', ytId: 'K0ibBPhiaG0', genre: 'pop' },
  { id: 'pop25', title: 'Galway Girl', artist: 'Ed Sheeran', ytId: '87gWaABqGYs', genre: 'pop' },
  { id: 'pop26', title: 'The A Team', artist: 'Ed Sheeran', ytId: 'UAWcs5H-qgQ', genre: 'pop' },
  { id: 'pop27', title: 'Shivers', artist: 'Ed Sheeran', ytId: 'Il0S8BoucSA', genre: 'pop' },
  { id: 'pop28', title: 'Bad Habits', artist: 'Ed Sheeran', ytId: 'orJSJGHjBLI', genre: 'pop' },
  { id: 'pop29', title: 'Sing', artist: 'Ed Sheeran', ytId: 'tlYcUqEPN58', genre: 'pop' },
  { id: 'pop30', title: 'Happier', artist: 'Ed Sheeran', ytId: 'iWBsZNgTfd4', genre: 'pop' },
  { id: 'pop31', title: 'Dive', artist: 'Ed Sheeran', ytId: '-RpOUDqfSoY', genre: 'pop' },
  // Justin Bieber
  { id: 'pop35', title: 'Sorry', artist: 'Justin Bieber', ytId: 'fRh_vgS2dFE', genre: 'pop' },
  { id: 'pop36', title: 'What Do You Mean', artist: 'Justin Bieber', ytId: 'DK_0jXPuIr0', genre: 'pop' },
  { id: 'pop37', title: 'Peaches', artist: 'Justin Bieber', ytId: 'tQ0yjYUFKAE', genre: 'pop' },
  { id: 'pop38', title: 'Stay', artist: 'Kid LAROI & Justin Bieber', ytId: 'kTJczUoc26U', genre: 'pop' },
  { id: 'pop39', title: 'Baby', artist: 'Justin Bieber ft. Ludacris', ytId: 'kffacxfA7G4', genre: 'pop' },
  { id: 'pop40', title: 'Love Yourself', artist: 'Justin Bieber', ytId: 'oyEuk8j8imI', genre: 'pop' },
  { id: 'pop41', title: 'Yummy', artist: 'Justin Bieber', ytId: '8EJ3zbKTWQ8', genre: 'pop' },
  { id: 'pop42', title: 'Ghost', artist: 'Justin Bieber', ytId: 'Fp8msa5uYsc', genre: 'pop' },
  { id: 'pop43', title: 'Intentions', artist: 'Justin Bieber ft. Quavo', ytId: 'lUFGy7DIwts', genre: 'pop' },
  { id: 'pop44', title: 'Despacito Remix', artist: 'Justin Bieber & Luis Fonsi', ytId: 'whwe0KD_rGw', genre: 'pop' },
  { id: 'pop45', title: 'Boyfriend', artist: 'Justin Bieber', ytId: 'MuIFhFeBP2k', genre: 'pop' },
  { id: 'pop46', title: 'Beauty And A Beat', artist: 'Justin Bieber ft. Nicki Minaj', ytId: 'Ys7-6_t7OEQ', genre: 'pop' },
  // Ariana Grande
  { id: 'pop50', title: 'Thank U Next', artist: 'Ariana Grande', ytId: 'gl1aHhXnN1k', genre: 'pop' },
  { id: 'pop51', title: '7 Rings', artist: 'Ariana Grande', ytId: 'QYh6mYIJG2Y', genre: 'pop' },
  { id: 'pop52', title: 'No Tears Left To Cry', artist: 'Ariana Grande', ytId: 'ffxKSjUwKdU', genre: 'pop' },
  { id: 'pop53', title: 'God Is A Woman', artist: 'Ariana Grande', ytId: 'kHLHSlExFis', genre: 'pop' },
  { id: 'pop54', title: 'Break Free', artist: 'Ariana Grande ft. Zedd', ytId: 'L8eRzOYhLuw', genre: 'pop' },
  { id: 'pop55', title: 'Problem', artist: 'Ariana Grande ft. Iggy Azalea', ytId: 'iS1g8G_njx8', genre: 'pop' },
  { id: 'pop56', title: 'Side To Side', artist: 'Ariana Grande ft. Nicki Minaj', ytId: 'SXiSVQZLje8', genre: 'pop' },
  { id: 'pop57', title: 'Into You', artist: 'Ariana Grande', ytId: '1ekZEVeXwek', genre: 'pop' },
  { id: 'pop58', title: 'Positions', artist: 'Ariana Grande', ytId: 'tcYodQoapMg', genre: 'pop' },
  { id: 'pop59', title: 'Stuck With U', artist: 'Ariana Grande & Justin Bieber', ytId: 'pE49WK-oNjU', genre: 'pop' },
  { id: 'pop60', title: 'One Last Time', artist: 'Ariana Grande', ytId: 'BPgEgaPk62M', genre: 'pop' },
  { id: 'pop61', title: 'Dangerous Woman', artist: 'Ariana Grande', ytId: '9WbCfHutDSE', genre: 'pop' },
  // Bruno Mars
  { id: 'pop65', title: 'Uptown Funk', artist: 'Bruno Mars', ytId: 'OPf0YbXqDm0', genre: 'pop' },
  { id: 'pop66', title: 'Just The Way You Are', artist: 'Bruno Mars', ytId: 'LjhCEhWiKXk', genre: 'pop' },
  { id: 'pop67', title: '24K Magic', artist: 'Bruno Mars', ytId: 'UqyT8IEBkvY', genre: 'pop' },
  { id: 'pop68', title: 'Thats What I Like', artist: 'Bruno Mars', ytId: 'PMivT7MJ41M', genre: 'pop' },
  { id: 'pop69', title: 'Grenade', artist: 'Bruno Mars', ytId: 'SR6iYWJxHqs', genre: 'pop' },
  { id: 'pop70', title: 'Locked Out Of Heaven', artist: 'Bruno Mars', ytId: 'e-fA-gBCkj0', genre: 'pop' },
  { id: 'pop71', title: 'When I Was Your Man', artist: 'Bruno Mars', ytId: 'ekzHIouo8Q4', genre: 'pop' },
  { id: 'pop72', title: 'Treasure', artist: 'Bruno Mars', ytId: 'nPvuNsRccVw', genre: 'pop' },
  { id: 'pop73', title: 'Finesse', artist: 'Bruno Mars ft. Cardi B', ytId: 'LsoLEjrDogU', genre: 'pop' },
  { id: 'pop74', title: 'Leave The Door Open', artist: 'Silk Sonic', ytId: 'adLGHcj_fmA', genre: 'pop' },
  { id: 'pop75', title: 'Smokin Out The Window', artist: 'Silk Sonic', ytId: 'fHBwmzCVyYk', genre: 'pop' },
  // The Weeknd
  { id: 'pop80', title: 'Blinding Lights', artist: 'The Weeknd', ytId: '4NRXx6U8ABQ', genre: 'pop' },
  { id: 'pop81', title: 'Save Your Tears', artist: 'The Weeknd', ytId: 'XXYlFuWEuKI', genre: 'pop' },
  { id: 'pop82', title: 'Starboy', artist: 'The Weeknd ft. Daft Punk', ytId: '34Na4j8AVgA', genre: 'pop' },
  { id: 'pop83', title: 'The Hills', artist: 'The Weeknd', ytId: 'yzTuBuRdAyA', genre: 'pop' },
  { id: 'pop84', title: 'Cant Feel My Face', artist: 'The Weeknd', ytId: 'KEI4qSrkPAs', genre: 'pop' },
  { id: 'pop85', title: 'I Feel It Coming', artist: 'The Weeknd ft. Daft Punk', ytId: 'qFLhGq0060w', genre: 'pop' },
  { id: 'pop86', title: 'Call Out My Name', artist: 'The Weeknd', ytId: 'M4ZoCHID9GI', genre: 'pop' },
  { id: 'pop87', title: 'Die For You', artist: 'The Weeknd', ytId: 'mTLQhPFx2nM', genre: 'pop' },
  { id: 'pop88', title: 'In Your Eyes', artist: 'The Weeknd', ytId: 'dqRZDebPIGs', genre: 'pop' },
  { id: 'pop89', title: 'Heartless', artist: 'The Weeknd', ytId: '1DpH-icPpl0', genre: 'pop' },
  { id: 'pop90', title: 'Often', artist: 'The Weeknd', ytId: 'JPIhUaONiLU', genre: 'pop' },
  { id: 'pop91', title: 'Earned It', artist: 'The Weeknd', ytId: 'waU75jdUnYw', genre: 'pop' },
  // Dua Lipa
  { id: 'pop95', title: 'Levitating', artist: 'Dua Lipa', ytId: 'TUVcZfQe-Kw', genre: 'pop' },
  { id: 'pop96', title: 'Dont Start Now', artist: 'Dua Lipa', ytId: 'oygrmJFKYZY', genre: 'pop' },
  { id: 'pop97', title: 'New Rules', artist: 'Dua Lipa', ytId: 'k2qgadSvNyU', genre: 'pop' },
  { id: 'pop98', title: 'Physical', artist: 'Dua Lipa', ytId: '9HDEHj2uj7Y', genre: 'pop' },
  { id: 'pop99', title: 'IDGAF', artist: 'Dua Lipa', ytId: 'Mgfe5tIwOj0', genre: 'pop' },
  { id: 'pop100', title: 'One Kiss', artist: 'Calvin Harris & Dua Lipa', ytId: 'DkeiKbqa02g', genre: 'pop' },
  { id: 'pop101', title: 'Break My Heart', artist: 'Dua Lipa', ytId: 'Nj2U6rhnucI', genre: 'pop' },
  { id: 'pop102', title: 'Kiss and Make Up', artist: 'Dua Lipa & BLACKPINK', ytId: 'PDQVQ3sEVTY', genre: 'pop' },
  { id: 'pop103', title: 'Cold Heart', artist: 'Elton John & Dua Lipa', ytId: 'qod03PVTLqk', genre: 'pop' },
  { id: 'pop104', title: 'Houdini', artist: 'Dua Lipa', ytId: 'WDuVu5cZyIs', genre: 'pop' },
  // Billie Eilish
  { id: 'pop110', title: 'Bad Guy', artist: 'Billie Eilish', ytId: 'DyDfgMOUjCI', genre: 'pop' },
  { id: 'pop111', title: 'Lovely', artist: 'Billie Eilish & Khalid', ytId: 'V1Pl8CzNzCw', genre: 'pop' },
  { id: 'pop112', title: 'Ocean Eyes', artist: 'Billie Eilish', ytId: 'viimfQi_pUw', genre: 'pop' },
  { id: 'pop113', title: 'When The Partys Over', artist: 'Billie Eilish', ytId: 'pbMwTqkKSps', genre: 'pop' },
  { id: 'pop114', title: 'Bury A Friend', artist: 'Billie Eilish', ytId: 'HUHC9tYz8ik', genre: 'pop' },
  { id: 'pop115', title: 'Therefore I Am', artist: 'Billie Eilish', ytId: 'RUQl6YcMalg', genre: 'pop' },
  { id: 'pop116', title: 'Everything I Wanted', artist: 'Billie Eilish', ytId: 'EgBJmlPo8Xw', genre: 'pop' },
  { id: 'pop117', title: 'Happier Than Ever', artist: 'Billie Eilish', ytId: '5GJWxDKyk3A', genre: 'pop' },
  { id: 'pop118', title: 'No Time To Die', artist: 'Billie Eilish', ytId: 'GB_S2qFh5lU', genre: 'pop' },
  { id: 'pop119', title: 'Birds Of A Feather', artist: 'Billie Eilish', ytId: '0o8XAL_RXBc', genre: 'pop' },
  // Harry Styles
  { id: 'pop125', title: 'As It Was', artist: 'Harry Styles', ytId: 'H5v3kku4y6Q', genre: 'pop' },
  { id: 'pop126', title: 'Watermelon Sugar', artist: 'Harry Styles', ytId: 'E07s5ZYygMg', genre: 'pop' },
  { id: 'pop127', title: 'Sign of the Times', artist: 'Harry Styles', ytId: 'qN4ooNx77u0', genre: 'pop' },
  { id: 'pop128', title: 'Adore You', artist: 'Harry Styles', ytId: 'VF-r5TtlT9w', genre: 'pop' },
  { id: 'pop129', title: 'Golden', artist: 'Harry Styles', ytId: 'P3cffdsEXXw', genre: 'pop' },
  { id: 'pop130', title: 'Late Night Talking', artist: 'Harry Styles', ytId: 'X9mxFcCfrFA', genre: 'pop' },
  { id: 'pop131', title: 'Falling', artist: 'Harry Styles', ytId: 'olGSAVOkkTI', genre: 'pop' },
  // More Pop
  { id: 'pop135', title: 'Flowers', artist: 'Miley Cyrus', ytId: 'G7KNmW9a75Y', genre: 'pop' },
  { id: 'pop136', title: 'Wrecking Ball', artist: 'Miley Cyrus', ytId: 'My2FRPA3Gf8', genre: 'pop' },
  { id: 'pop137', title: 'Midnight Sky', artist: 'Miley Cyrus', ytId: 'aS1no1myeTM', genre: 'pop' },
  { id: 'pop138', title: 'Party In The USA', artist: 'Miley Cyrus', ytId: 'M11SvDtPBhA', genre: 'pop' },
  { id: 'pop139', title: 'We Cant Stop', artist: 'Miley Cyrus', ytId: 'LrUvu1mlWco', genre: 'pop' },
  { id: 'pop140', title: 'Say So', artist: 'Doja Cat', ytId: 'pok8H_KF1FA', genre: 'pop' },
  { id: 'pop141', title: 'Kiss Me More', artist: 'Doja Cat ft. SZA', ytId: '0EVVKs6DQLo', genre: 'pop' },
  { id: 'pop142', title: 'Need To Know', artist: 'Doja Cat', ytId: 'acp-rR69GZc', genre: 'pop' },
  { id: 'pop143', title: 'Woman', artist: 'Doja Cat', ytId: 'Iq5gesj8bhY', genre: 'pop' },
  { id: 'pop144', title: 'Streets', artist: 'Doja Cat', ytId: 'eN4dDc-EvFY', genre: 'pop' },
  { id: 'pop145', title: 'Espresso', artist: 'Sabrina Carpenter', ytId: 'eVli-tstM5E', genre: 'pop' },
  { id: 'pop146', title: 'Please Please Please', artist: 'Sabrina Carpenter', ytId: 'cF1Na4AIecM', genre: 'pop' },
  { id: 'pop147', title: 'Drivers License', artist: 'Olivia Rodrigo', ytId: 'ZmDBbnmKpqQ', genre: 'pop' },
  { id: 'pop148', title: 'Good 4 U', artist: 'Olivia Rodrigo', ytId: 'gNi_6U5Pm_o', genre: 'pop' },
  { id: 'pop149', title: 'Vampire', artist: 'Olivia Rodrigo', ytId: 'RlPNh_PBZb4', genre: 'pop' },
  { id: 'pop150', title: 'Deja Vu', artist: 'Olivia Rodrigo', ytId: 'cii6ruuycQA', genre: 'pop' },
  { id: 'pop151', title: 'Traitor', artist: 'Olivia Rodrigo', ytId: 'N9GIvBs0kFs', genre: 'pop' },
  { id: 'pop152', title: 'Dance Monkey', artist: 'Tones and I', ytId: 'q0hyYWKXF0Q', genre: 'pop' },
  { id: 'pop153', title: 'Attention', artist: 'Charlie Puth', ytId: 'nfs8NYg7yQM', genre: 'pop' },
  { id: 'pop154', title: 'We Dont Talk Anymore', artist: 'Charlie Puth ft. Selena', ytId: '3AtDnEC4zak', genre: 'pop' },
  { id: 'pop155', title: 'Chandelier', artist: 'Sia', ytId: '2vjPBrBU-TM', genre: 'pop' },
  { id: 'pop156', title: 'Cheap Thrills', artist: 'Sia', ytId: '31crA53Dgu0', genre: 'pop' },
  { id: 'pop157', title: 'Elastic Heart', artist: 'Sia', ytId: 'KWZGAExj-es', genre: 'pop' },
  { id: 'pop158', title: 'Roar', artist: 'Katy Perry', ytId: 'CevxZvSJLk8', genre: 'pop' },
  { id: 'pop159', title: 'Firework', artist: 'Katy Perry', ytId: 'QGJuMBdaqIw', genre: 'pop' },
  { id: 'pop160', title: 'Dark Horse', artist: 'Katy Perry ft. Juicy J', ytId: '0KSOMA3QBU0', genre: 'pop' },
  { id: 'pop161', title: 'Teenage Dream', artist: 'Katy Perry', ytId: '98WtmW-lfeE', genre: 'pop' },
  { id: 'pop162', title: 'California Gurls', artist: 'Katy Perry ft. Snoop', ytId: 'F57P9C4SAW4', genre: 'pop' },
  { id: 'pop163', title: 'Hot N Cold', artist: 'Katy Perry', ytId: 'kTHNpusq654', genre: 'pop' },
  { id: 'pop164', title: 'Rolling in the Deep', artist: 'Adele', ytId: 'rYEDA3JcQqw', genre: 'pop' },
  { id: 'pop165', title: 'Hello', artist: 'Adele', ytId: 'YQHsXMglC9A', genre: 'pop' },
  { id: 'pop166', title: 'Someone Like You', artist: 'Adele', ytId: 'hLQl3WQQoQ0', genre: 'pop' },
  { id: 'pop167', title: 'Set Fire to the Rain', artist: 'Adele', ytId: 'Ri7-vnrJD3k', genre: 'pop' },
  { id: 'pop168', title: 'Easy On Me', artist: 'Adele', ytId: 'U3ASj1L6_sY', genre: 'pop' },
  { id: 'pop169', title: 'Somebody That I Used To Know', artist: 'Gotye', ytId: '8UVNT4wvIGY', genre: 'pop' },
  { id: 'pop170', title: 'Counting Stars', artist: 'OneRepublic', ytId: 'hT_nvWreIhg', genre: 'pop' },
  { id: 'pop171', title: 'Apologize', artist: 'OneRepublic', ytId: 'ZSM3w1v-A_Y', genre: 'pop' },
  { id: 'pop172', title: 'Secrets', artist: 'OneRepublic', ytId: 'qHm9MG9xw1o', genre: 'pop' },
  { id: 'pop173', title: 'Feel Good Inc', artist: 'Gorillaz', ytId: 'HyHNuVaZJ-k', genre: 'pop' },
  { id: 'pop174', title: 'Clint Eastwood', artist: 'Gorillaz', ytId: '1V_xRb0x9aw', genre: 'pop' },
  { id: 'pop175', title: 'On Top Of The World', artist: 'Imagine Dragons', ytId: 'g8PrTzLaLHc', genre: 'pop' },
  { id: 'pop176', title: 'Whatever It Takes', artist: 'Imagine Dragons', ytId: 'gOsM-DYAEhY', genre: 'pop' },
  { id: 'pop177', title: 'Bones', artist: 'Imagine Dragons', ytId: 'TO-_3tck2tg', genre: 'pop' },
  { id: 'pop178', title: 'Enemy', artist: 'Imagine Dragons', ytId: 'D9G1VOjN_84', genre: 'pop' },
  { id: 'pop179', title: 'Radioactive', artist: 'Imagine Dragons', ytId: 'ktvTqknDobU', genre: 'pop' },
  { id: 'pop180', title: 'Believer', artist: 'Imagine Dragons', ytId: '7wtfhZwyrcc', genre: 'pop' },

  // ===================== R&B (100+) =====================
  // SZA
  { id: 'rnb1', title: 'Kill Bill', artist: 'SZA', ytId: 'hFBPE-ub69Q', genre: 'rnb' },
  { id: 'rnb2', title: 'Good Days', artist: 'SZA', ytId: '2p3zZoraK9g', genre: 'rnb' },
  { id: 'rnb3', title: 'The Weekend', artist: 'SZA', ytId: '6hRSgoU-E3g', genre: 'rnb' },
  { id: 'rnb4', title: 'Love Galore', artist: 'SZA ft. Travis Scott', ytId: 'hHXfCOjb3fk', genre: 'rnb' },
  { id: 'rnb5', title: 'Broken Clocks', artist: 'SZA', ytId: 'FdVIjdD9kT0', genre: 'rnb' },
  { id: 'rnb6', title: 'Shirt', artist: 'SZA', ytId: 'z8YYijVuEgU', genre: 'rnb' },
  { id: 'rnb7', title: 'Snooze', artist: 'SZA', ytId: 'LIbtdJNy0xw', genre: 'rnb' },
  { id: 'rnb8', title: 'Nobody Gets Me', artist: 'SZA', ytId: 'hLiQoX5CjOU', genre: 'rnb' },
  // Khalid
  { id: 'rnb10', title: 'Location', artist: 'Khalid', ytId: 'by3yRdlQvzs', genre: 'rnb' },
  { id: 'rnb11', title: 'Young Dumb & Broke', artist: 'Khalid', ytId: 'IPfJnp1guPc', genre: 'rnb' },
  { id: 'rnb12', title: 'Talk', artist: 'Khalid', ytId: 'hE2Ira-Cwxo', genre: 'rnb' },
  { id: 'rnb13', title: 'Better', artist: 'Khalid', ytId: 'x3bfa3DZ8JM', genre: 'rnb' },
  { id: 'rnb14', title: 'Eastside', artist: 'Benny Blanco, Halsey & Khalid', ytId: '56WBK4ZK_cw', genre: 'rnb' },
  { id: 'rnb15', title: '8TEEN', artist: 'Khalid', ytId: '8i1eCsJm_zc', genre: 'rnb' },
  { id: 'rnb16', title: 'Lovely', artist: 'Billie Eilish & Khalid', ytId: 'V1Pl8CzNzCw', genre: 'rnb' },
  // Daniel Caesar
  { id: 'rnb20', title: 'Best Part', artist: 'Daniel Caesar ft. H.E.R.', ytId: 'vBy7FaapGRo', genre: 'rnb' },
  { id: 'rnb21', title: 'Get You', artist: 'Daniel Caesar ft. Kali Uchis', ytId: 'uQFVqltOXRg', genre: 'rnb' },
  { id: 'rnb22', title: 'Japanese Denim', artist: 'Daniel Caesar', ytId: 'wFLoYq6VyFc', genre: 'rnb' },
  { id: 'rnb23', title: 'Cyanide', artist: 'Daniel Caesar', ytId: 'mN2_-tGfhj0', genre: 'rnb' },
  // Frank Ocean
  { id: 'rnb30', title: 'Thinkin Bout You', artist: 'Frank Ocean', ytId: 'Y9MWHprLMZs', genre: 'rnb' },
  { id: 'rnb31', title: 'Nights', artist: 'Frank Ocean', ytId: 'r4l9bFqgMaQ', genre: 'rnb' },
  { id: 'rnb32', title: 'Lost', artist: 'Frank Ocean', ytId: 'WVs5H-TqWjc', genre: 'rnb' },
  { id: 'rnb33', title: 'Pink + White', artist: 'Frank Ocean', ytId: 'uzS3WG6__G4', genre: 'rnb' },
  { id: 'rnb34', title: 'Ivy', artist: 'Frank Ocean', ytId: 'AE005nZeF-A', genre: 'rnb' },
  { id: 'rnb35', title: 'Self Control', artist: 'Frank Ocean', ytId: 'BME88lS6aVY', genre: 'rnb' },
  // Chris Brown
  { id: 'rnb40', title: 'No Guidance', artist: 'Chris Brown ft. Drake', ytId: 'AoLfK5FNjxk', genre: 'rnb' },
  { id: 'rnb41', title: 'With You', artist: 'Chris Brown', ytId: 'S_XP19ct-zQ', genre: 'rnb' },
  { id: 'rnb42', title: 'Forever', artist: 'Chris Brown', ytId: '5sMKX22BHeE', genre: 'rnb' },
  { id: 'rnb43', title: 'Yeah 3x', artist: 'Chris Brown', ytId: 'oSGvvB9Skn0', genre: 'rnb' },
  { id: 'rnb44', title: 'Look At Me Now', artist: 'Chris Brown ft. Busta', ytId: '8gyLR4NfMiI', genre: 'rnb' },
  { id: 'rnb45', title: 'Under The Influence', artist: 'Chris Brown', ytId: '2VdEVzjKRGg', genre: 'rnb' },
  { id: 'rnb46', title: 'Loyal', artist: 'Chris Brown ft. Lil Wayne', ytId: 'JXRN_LkCa_o', genre: 'rnb' },
  // Usher
  { id: 'rnb50', title: 'Yeah!', artist: 'Usher ft. Lil Jon', ytId: 'GxBSyx85Kp8', genre: 'rnb' },
  { id: 'rnb51', title: 'DJ Got Us Fallin In Love', artist: 'Usher ft. Pitbull', ytId: 'C-dvTjK_07c', genre: 'rnb' },
  { id: 'rnb52', title: 'OMG', artist: 'Usher ft. will.i.am', ytId: '1RnPB76mjxI', genre: 'rnb' },
  { id: 'rnb53', title: 'U Got It Bad', artist: 'Usher', ytId: 'q3JY02dI-I8', genre: 'rnb' },
  { id: 'rnb54', title: 'Confessions Part II', artist: 'Usher', ytId: '5a8HN_BdqFc', genre: 'rnb' },
  { id: 'rnb55', title: 'Burn', artist: 'Usher', ytId: 'Bxmkiy9txBE', genre: 'rnb' },
  { id: 'rnb56', title: 'My Boo', artist: 'Usher & Alicia Keys', ytId: 'kYD0iiVYs7A', genre: 'rnb' },
  // More R&B
  { id: 'rnb60', title: 'Focus', artist: 'H.E.R.', ytId: 'CxHGpRF8mdo', genre: 'rnb' },
  { id: 'rnb61', title: 'Damage', artist: 'H.E.R.', ytId: 'i-K9sWdZdWk', genre: 'rnb' },
  { id: 'rnb62', title: 'Best Part', artist: 'H.E.R. ft. Daniel Caesar', ytId: 'vBy7FaapGRo', genre: 'rnb' },
  { id: 'rnb63', title: 'Electric', artist: 'Alicia Keys', ytId: '0hT0zVEsNRw', genre: 'rnb' },
  { id: 'rnb64', title: 'If I Aint Got You', artist: 'Alicia Keys', ytId: 'Ju8Hr50Ckwk', genre: 'rnb' },
  { id: 'rnb65', title: 'No One', artist: 'Alicia Keys', ytId: 'rywUS-ohqeE', genre: 'rnb' },
  { id: 'rnb66', title: 'Girl On Fire', artist: 'Alicia Keys', ytId: 'J91ti_MpdHA', genre: 'rnb' },
  { id: 'rnb67', title: 'Fallin', artist: 'Alicia Keys', ytId: 'Urdlvw0TAPE', genre: 'rnb' },
  { id: 'rnb68', title: 'Crew', artist: 'GoldLink ft. Brent Faiyaz', ytId: 'nhNqbe6QENY', genre: 'rnb' },
  { id: 'rnb69', title: 'Gravity', artist: 'Brent Faiyaz', ytId: 'Ycl5T7CKBGU', genre: 'rnb' },
  { id: 'rnb70', title: 'Trust', artist: 'Brent Faiyaz', ytId: 'ZCwG4kh6gTw', genre: 'rnb' },
  { id: 'rnb71', title: 'Wasting Time', artist: 'Brent Faiyaz', ytId: '7HdN02LwVok', genre: 'rnb' },
  { id: 'rnb72', title: 'After Hours', artist: 'The Weeknd', ytId: 'ygTZZpVkmKg', genre: 'rnb' },
  { id: 'rnb73', title: 'Wicked Games', artist: 'The Weeknd', ytId: 'O1OTWCd40Ac', genre: 'rnb' },
  { id: 'rnb74', title: 'The Morning', artist: 'The Weeknd', ytId: '5TAko3RH0bk', genre: 'rnb' },
  { id: 'rnb75', title: 'House of Balloons', artist: 'The Weeknd', ytId: '5TAko3RH0bk', genre: 'rnb' },
  { id: 'rnb76', title: 'All I Wanna Do', artist: 'Jay Park', ytId: 'eISomx-VMow', genre: 'rnb' },
  { id: 'rnb77', title: 'Love Again', artist: 'Dua Lipa', ytId: 'BC19kwABFwc', genre: 'rnb' },
  { id: 'rnb78', title: 'Get Lucky', artist: 'Daft Punk ft. Pharrell', ytId: '5NV6Rdv1a3I', genre: 'rnb' },
  { id: 'rnb79', title: 'Happy', artist: 'Pharrell Williams', ytId: 'ZbZSe6N_BXs', genre: 'rnb' },
  { id: 'rnb80', title: 'Blurred Lines', artist: 'Robin Thicke ft. T.I. Pharrell', ytId: 'yyDUC1LUXSU', genre: 'rnb' },
];

  // ===================== ROCK (100+) =====================
  // Imagine Dragons (already in pop, but adding rock versions)
  { id: 'rock1', title: 'Thunder', artist: 'Imagine Dragons', ytId: 'fKopy74weus', genre: 'rock' },
  { id: 'rock2', title: 'Demons', artist: 'Imagine Dragons', ytId: 'mWRsgZuwf_8', genre: 'rock' },
  { id: 'rock3', title: 'Natural', artist: 'Imagine Dragons', ytId: '0I647GU3Jsc', genre: 'rock' },
  // Twenty One Pilots
  { id: 'rock10', title: 'Stressed Out', artist: 'Twenty One Pilots', ytId: 'pXRviuL6vMY', genre: 'rock' },
  { id: 'rock11', title: 'Heathens', artist: 'Twenty One Pilots', ytId: 'UprcpdwuwCg', genre: 'rock' },
  { id: 'rock12', title: 'Ride', artist: 'Twenty One Pilots', ytId: 'Pw-0pbY9JeU', genre: 'rock' },
  { id: 'rock13', title: 'Tear In My Heart', artist: 'Twenty One Pilots', ytId: 'nky4me4NP70', genre: 'rock' },
  { id: 'rock14', title: 'Car Radio', artist: 'Twenty One Pilots', ytId: '92XVwY54h5k', genre: 'rock' },
  { id: 'rock15', title: 'Lane Boy', artist: 'Twenty One Pilots', ytId: 'ywvRgGAd2XI', genre: 'rock' },
  { id: 'rock16', title: 'Jumpsuit', artist: 'Twenty One Pilots', ytId: 'UOUBW8bkjQ4', genre: 'rock' },
  { id: 'rock17', title: 'Chlorine', artist: 'Twenty One Pilots', ytId: 'eJnQBXmZ7Ek', genre: 'rock' },
  // Coldplay
  { id: 'rock20', title: 'Viva La Vida', artist: 'Coldplay', ytId: 'dvgZkm1xWPE', genre: 'rock' },
  { id: 'rock21', title: 'The Scientist', artist: 'Coldplay', ytId: 'RB-RcX5DS5A', genre: 'rock' },
  { id: 'rock22', title: 'Fix You', artist: 'Coldplay', ytId: 'k4V3Mo61fJM', genre: 'rock' },
  { id: 'rock23', title: 'Clocks', artist: 'Coldplay', ytId: 'd020hcWA_Wg', genre: 'rock' },
  { id: 'rock24', title: 'Yellow', artist: 'Coldplay', ytId: 'yKNxeF4KMsY', genre: 'rock' },
  { id: 'rock25', title: 'Paradise', artist: 'Coldplay', ytId: '1G4isv_Fylg', genre: 'rock' },
  { id: 'rock26', title: 'Something Just Like This', artist: 'Coldplay & Chainsmokers', ytId: 'FM7MFYoylVs', genre: 'rock' },
  { id: 'rock27', title: 'A Sky Full of Stars', artist: 'Coldplay', ytId: 'VPRjCeoBqrI', genre: 'rock' },
  { id: 'rock28', title: 'Adventure of a Lifetime', artist: 'Coldplay', ytId: 'QtXby3twMmI', genre: 'rock' },
  { id: 'rock29', title: 'My Universe', artist: 'Coldplay & BTS', ytId: '3YqPKLZF_WU', genre: 'rock' },
  { id: 'rock30', title: 'Hymn For The Weekend', artist: 'Coldplay ft. Beyonce', ytId: 'YykjpeuMNEk', genre: 'rock' },
  { id: 'rock31', title: 'Speed of Sound', artist: 'Coldplay', ytId: '0k_1kvDh2UA', genre: 'rock' },
  // Queen
  { id: 'rock35', title: 'Bohemian Rhapsody', artist: 'Queen', ytId: 'fJ9rUzIMcZQ', genre: 'rock' },
  { id: 'rock36', title: 'We Will Rock You', artist: 'Queen', ytId: '-tJYN-eG1zk', genre: 'rock' },
  { id: 'rock37', title: 'We Are The Champions', artist: 'Queen', ytId: '04854XqcfCY', genre: 'rock' },
  { id: 'rock38', title: 'Dont Stop Me Now', artist: 'Queen', ytId: 'HgzGwKwLmgM', genre: 'rock' },
  { id: 'rock39', title: 'Somebody To Love', artist: 'Queen', ytId: 'kijpcUv-b8M', genre: 'rock' },
  { id: 'rock40', title: 'Another One Bites The Dust', artist: 'Queen', ytId: 'rY0WxgSXdEE', genre: 'rock' },
  { id: 'rock41', title: 'Radio Ga Ga', artist: 'Queen', ytId: 'azdwsXLmrHE', genre: 'rock' },
  { id: 'rock42', title: 'Under Pressure', artist: 'Queen & David Bowie', ytId: 'a01QQZyl-_I', genre: 'rock' },
  { id: 'rock43', title: 'I Want To Break Free', artist: 'Queen', ytId: 'f4Mc-NYPHaQ', genre: 'rock' },
  { id: 'rock44', title: 'Killer Queen', artist: 'Queen', ytId: '2ZBtPf7FOoM', genre: 'rock' },
  // Classic Rock
  { id: 'rock50', title: 'Smells Like Teen Spirit', artist: 'Nirvana', ytId: 'hTWKbfoikeg', genre: 'rock' },
  { id: 'rock51', title: 'Come As You Are', artist: 'Nirvana', ytId: 'vabnZ9-ex7o', genre: 'rock' },
  { id: 'rock52', title: 'In Bloom', artist: 'Nirvana', ytId: 'PbgKEjNBHqM', genre: 'rock' },
  { id: 'rock53', title: 'Lithium', artist: 'Nirvana', ytId: 'pkcJEvMcnEg', genre: 'rock' },
  { id: 'rock54', title: 'Heart-Shaped Box', artist: 'Nirvana', ytId: 'n6P0SitRwy8', genre: 'rock' },
  { id: 'rock55', title: 'Stairway To Heaven', artist: 'Led Zeppelin', ytId: 'QkF3oxziUI4', genre: 'rock' },
  { id: 'rock56', title: 'Kashmir', artist: 'Led Zeppelin', ytId: 'tzVJPgCn-Z8', genre: 'rock' },
  { id: 'rock57', title: 'Whole Lotta Love', artist: 'Led Zeppelin', ytId: 'HQmmM_qwG4k', genre: 'rock' },
  { id: 'rock58', title: 'Black Dog', artist: 'Led Zeppelin', ytId: 'yBuub4Xe1mw', genre: 'rock' },
  { id: 'rock59', title: 'Sweet Child O Mine', artist: 'Guns N Roses', ytId: '1w7OgIMMRc4', genre: 'rock' },
  { id: 'rock60', title: 'Welcome To The Jungle', artist: 'Guns N Roses', ytId: 'o1tj2zJ2Wvg', genre: 'rock' },
  { id: 'rock61', title: 'Paradise City', artist: 'Guns N Roses', ytId: 'Rbm6GXllBiw', genre: 'rock' },
  { id: 'rock62', title: 'November Rain', artist: 'Guns N Roses', ytId: '8SbUC-UaAxE', genre: 'rock' },
  { id: 'rock63', title: 'Patience', artist: 'Guns N Roses', ytId: 'ErvgV4P6Fzc', genre: 'rock' },
  { id: 'rock64', title: 'Hotel California', artist: 'Eagles', ytId: 'BciS5krYL80', genre: 'rock' },
  { id: 'rock65', title: 'Take It Easy', artist: 'Eagles', ytId: '4WVTG3BPiE0', genre: 'rock' },
  { id: 'rock66', title: 'Back In Black', artist: 'AC/DC', ytId: 'pAgnJDJN4VA', genre: 'rock' },
  { id: 'rock67', title: 'Highway To Hell', artist: 'AC/DC', ytId: 'l482T0yNkeo', genre: 'rock' },
  { id: 'rock68', title: 'Thunderstruck', artist: 'AC/DC', ytId: 'v2AC41dglnM', genre: 'rock' },
  { id: 'rock69', title: 'TNT', artist: 'AC/DC', ytId: '44XYEeD1A1U', genre: 'rock' },
  { id: 'rock70', title: 'You Shook Me All Night Long', artist: 'AC/DC', ytId: 'Lo2qQmj0_h4', genre: 'rock' },
  { id: 'rock71', title: 'Mr. Brightside', artist: 'The Killers', ytId: 'gGdGFtwCNBE', genre: 'rock' },
  { id: 'rock72', title: 'Somebody Told Me', artist: 'The Killers', ytId: 'Y5fBdpreJiU', genre: 'rock' },
  { id: 'rock73', title: 'Human', artist: 'The Killers', ytId: 'RIZdjT1472Y', genre: 'rock' },
  { id: 'rock74', title: 'When You Were Young', artist: 'The Killers', ytId: 'ff0oWESdmH0', genre: 'rock' },
  { id: 'rock75', title: 'Chasing Cars', artist: 'Snow Patrol', ytId: 'GemKqzILV4w', genre: 'rock' },
  { id: 'rock76', title: 'Use Somebody', artist: 'Kings of Leon', ytId: 'gnhXHvRoUd0', genre: 'rock' },
  { id: 'rock77', title: 'Sex On Fire', artist: 'Kings of Leon', ytId: 'RF0HhrwIwp0', genre: 'rock' },
  { id: 'rock78', title: 'Seven Nation Army', artist: 'The White Stripes', ytId: '0J2QdDbelmY', genre: 'rock' },
  { id: 'rock79', title: 'Creep', artist: 'Radiohead', ytId: 'XFkzRNyygfk', genre: 'rock' },
  { id: 'rock80', title: 'Karma Police', artist: 'Radiohead', ytId: '1uYWYWPc9HU', genre: 'rock' },
  { id: 'rock81', title: 'No Surprises', artist: 'Radiohead', ytId: 'u5CVsCnxyXg', genre: 'rock' },
  { id: 'rock82', title: 'High and Dry', artist: 'Radiohead', ytId: '7qFfFVSerQo', genre: 'rock' },
  { id: 'rock83', title: 'Dream On', artist: 'Aerosmith', ytId: '89dGC8de0CA', genre: 'rock' },
  { id: 'rock84', title: 'I Dont Want To Miss A Thing', artist: 'Aerosmith', ytId: 'JkK8g6FMEXE', genre: 'rock' },
  { id: 'rock85', title: 'Walk This Way', artist: 'Aerosmith', ytId: '4B_UYYPb-Gk', genre: 'rock' },
  { id: 'rock86', title: 'Livin On A Prayer', artist: 'Bon Jovi', ytId: 'lDK9QqIzhwk', genre: 'rock' },
  { id: 'rock87', title: 'Its My Life', artist: 'Bon Jovi', ytId: 'vx2u5uUu3DE', genre: 'rock' },
  { id: 'rock88', title: 'Wanted Dead Or Alive', artist: 'Bon Jovi', ytId: 'SRvCvsRp5ho', genre: 'rock' },
  { id: 'rock89', title: 'You Give Love A Bad Name', artist: 'Bon Jovi', ytId: 'S9tKwSboJeg', genre: 'rock' },
  { id: 'rock90', title: 'Summer of 69', artist: 'Bryan Adams', ytId: '9f06QZCVUHg', genre: 'rock' },
  { id: 'rock91', title: 'Everything I Do', artist: 'Bryan Adams', ytId: 'y0vFMw7lFEY', genre: 'rock' },
  { id: 'rock92', title: 'Free Fallin', artist: 'Tom Petty', ytId: '1lWJXDG2i0A', genre: 'rock' },
  { id: 'rock93', title: 'American Girl', artist: 'Tom Petty', ytId: 'SIhb-kNvL6M', genre: 'rock' },
  { id: 'rock94', title: 'Born To Run', artist: 'Bruce Springsteen', ytId: 'IxuThNgl3YA', genre: 'rock' },
  { id: 'rock95', title: 'Dancing In The Dark', artist: 'Bruce Springsteen', ytId: '129kuDCQtHs', genre: 'rock' },

  // ===================== ELECTRONIC / EDM (100+) =====================
  // Avicii
  { id: 'edm1', title: 'Wake Me Up', artist: 'Avicii', ytId: 'IcrbM1l_BoI', genre: 'electronic' },
  { id: 'edm2', title: 'Levels', artist: 'Avicii', ytId: '_ovdm2yX4MA', genre: 'electronic' },
  { id: 'edm3', title: 'The Nights', artist: 'Avicii', ytId: 'UtF6Jej8yb4', genre: 'electronic' },
  { id: 'edm4', title: 'Hey Brother', artist: 'Avicii', ytId: 'YxIiPLVR6NA', genre: 'electronic' },
  { id: 'edm5', title: 'Waiting For Love', artist: 'Avicii', ytId: 'cHHLHGNpCSA', genre: 'electronic' },
  { id: 'edm6', title: 'Without You', artist: 'Avicii ft. Sandro Cavazza', ytId: 'WoHxoz_0ykI', genre: 'electronic' },
  { id: 'edm7', title: 'Addicted To You', artist: 'Avicii', ytId: 'Qc9c12q3mrc', genre: 'electronic' },
  { id: 'edm8', title: 'Silhouettes', artist: 'Avicii', ytId: '6VJBBUqr1wM', genre: 'electronic' },
  { id: 'edm9', title: 'You Make Me', artist: 'Avicii', ytId: '2GADx4Hy-Gg', genre: 'electronic' },
  // Marshmello
  { id: 'edm15', title: 'Alone', artist: 'Marshmello', ytId: 'ALZHF5UqnU4', genre: 'electronic' },
  { id: 'edm16', title: 'Happier', artist: 'Marshmello ft. Bastille', ytId: 'm7Bc3pLyij0', genre: 'electronic' },
  { id: 'edm17', title: 'Silence', artist: 'Marshmello ft. Khalid', ytId: 'Tx1sqYc3qas', genre: 'electronic' },
  { id: 'edm18', title: 'Friends', artist: 'Marshmello & Anne-Marie', ytId: 'CY8E6N5Nzec', genre: 'electronic' },
  { id: 'edm19', title: 'Wolves', artist: 'Selena Gomez & Marshmello', ytId: 'cH4E_t3m3xM', genre: 'electronic' },
  { id: 'edm20', title: 'Here With Me', artist: 'Marshmello ft. CHVRCHES', ytId: 'T0lLfSA-P14', genre: 'electronic' },
  { id: 'edm21', title: 'Blocks', artist: 'Marshmello', ytId: 'T2nHgMAWpIs', genre: 'electronic' },
  { id: 'edm22', title: 'Moving On', artist: 'Marshmello', ytId: 'yU0tnrEk8H4', genre: 'electronic' },
  // Alan Walker
  { id: 'edm25', title: 'Faded', artist: 'Alan Walker', ytId: '60ItHLz5WEA', genre: 'electronic' },
  { id: 'edm26', title: 'Alone', artist: 'Alan Walker', ytId: '1-xTEwGe3Mg', genre: 'electronic' },
  { id: 'edm27', title: 'Darkside', artist: 'Alan Walker', ytId: 'M-P4QBt-FWw', genre: 'electronic' },
  { id: 'edm28', title: 'The Spectre', artist: 'Alan Walker', ytId: 'wJnBTPUQS5A', genre: 'electronic' },
  { id: 'edm29', title: 'On My Way', artist: 'Alan Walker ft. Sabrina', ytId: 'dhYOPzcsbGM', genre: 'electronic' },
  { id: 'edm30', title: 'Lily', artist: 'Alan Walker', ytId: 'r0dT5iyDvwU', genre: 'electronic' },
  { id: 'edm31', title: 'All Falls Down', artist: 'Alan Walker', ytId: '6RLLOEzdxsM', genre: 'electronic' },
  { id: 'edm32', title: 'Diamond Heart', artist: 'Alan Walker', ytId: 'sJXZ9Dok7u8', genre: 'electronic' },
  // Martin Garrix
  { id: 'edm35', title: 'Animals', artist: 'Martin Garrix', ytId: 'gCYcHz2k5x0', genre: 'electronic' },
  { id: 'edm36', title: 'In The Name Of Love', artist: 'Martin Garrix & Bebe Rexha', ytId: 'RnBT9uUYb1w', genre: 'electronic' },
  { id: 'edm37', title: 'Scared To Be Lonely', artist: 'Martin Garrix & Dua Lipa', ytId: 'e2vBLd5Egnk', genre: 'electronic' },
  { id: 'edm38', title: 'High On Life', artist: 'Martin Garrix ft. Bonn', ytId: 'Lpjcm28zC0k', genre: 'electronic' },
  { id: 'edm39', title: 'So Far Away', artist: 'Martin Garrix ft. David Guetta', ytId: 'o_xUq4w7dMo', genre: 'electronic' },
  // The Chainsmokers
  { id: 'edm45', title: 'Closer', artist: 'The Chainsmokers ft. Halsey', ytId: 'PT2_F-1esPk', genre: 'electronic' },
  { id: 'edm46', title: 'Dont Let Me Down', artist: 'The Chainsmokers ft. Daya', ytId: 'Io0fBr1XBUA', genre: 'electronic' },
  { id: 'edm47', title: 'Something Just Like This', artist: 'Chainsmokers & Coldplay', ytId: 'FM7MFYoylVs', genre: 'electronic' },
  { id: 'edm48', title: 'Roses', artist: 'The Chainsmokers ft. ROZES', ytId: 'FyASdjZE0R0', genre: 'electronic' },
  { id: 'edm49', title: 'Paris', artist: 'The Chainsmokers', ytId: 'RhU9MZ98jxo', genre: 'electronic' },
  { id: 'edm50', title: 'Selfie', artist: 'The Chainsmokers', ytId: 'kdemFfbS5H0', genre: 'electronic' },
  { id: 'edm51', title: 'All We Know', artist: 'The Chainsmokers ft. Phoebe', ytId: 'lEi_XBg2Fpk', genre: 'electronic' },
  // David Guetta
  { id: 'edm55', title: 'Titanium', artist: 'David Guetta ft. Sia', ytId: 'JRfuAukYTKg', genre: 'electronic' },
  { id: 'edm56', title: 'Hey Mama', artist: 'David Guetta ft. Nicki Minaj', ytId: 'uO59tfQ2TbA', genre: 'electronic' },
  { id: 'edm57', title: 'Turn Me On', artist: 'David Guetta ft. Nicki Minaj', ytId: 'bN0bHdF4UkQ', genre: 'electronic' },
  { id: 'edm58', title: 'When Love Takes Over', artist: 'David Guetta ft. Kelly', ytId: 'NCz6gLdGm6I', genre: 'electronic' },
  { id: 'edm59', title: 'Without You', artist: 'David Guetta ft. Usher', ytId: 'jUe8uoKdHao', genre: 'electronic' },
  { id: 'edm60', title: 'Dangerous', artist: 'David Guetta ft. Sam Martin', ytId: 'cZD5i9bmTzE', genre: 'electronic' },
  { id: 'edm61', title: 'Sexy Bitch', artist: 'David Guetta ft. Akon', ytId: 'j3IJQpMrVJI', genre: 'electronic' },
  { id: 'edm62', title: 'Play Hard', artist: 'David Guetta ft. Ne-Yo', ytId: '5dbEhBKGOtY', genre: 'electronic' },
  // More EDM
  { id: 'edm65', title: 'Lean On', artist: 'Major Lazer & DJ Snake', ytId: 'YqeW9_5kURI', genre: 'electronic' },
  { id: 'edm66', title: 'Light It Up', artist: 'Major Lazer', ytId: 'r2LpOUwca94', genre: 'electronic' },
  { id: 'edm67', title: 'Cold Water', artist: 'Major Lazer ft. Justin Bieber', ytId: 'a59gmGkq_pw', genre: 'electronic' },
  { id: 'edm68', title: 'Taki Taki', artist: 'DJ Snake ft. Cardi B', ytId: 'ixkoVwKQaJg', genre: 'electronic' },
  { id: 'edm69', title: 'Loco Contigo', artist: 'DJ Snake ft. J Balvin', ytId: 'Ll0vq6yRiYA', genre: 'electronic' },
  { id: 'edm70', title: 'Magenta Riddim', artist: 'DJ Snake', ytId: 'op4B9sNGi0k', genre: 'electronic' },
  { id: 'edm71', title: 'Let Me Love You', artist: 'DJ Snake ft. Justin Bieber', ytId: 'B-rnM-MwRHY', genre: 'electronic' },
  { id: 'edm72', title: 'Where Are U Now', artist: 'Skrillex & Diplo ft. Justin', ytId: 'nntGTK2Fhb0', genre: 'electronic' },
  { id: 'edm73', title: 'Bangarang', artist: 'Skrillex', ytId: 'YJVmu6yttiw', genre: 'electronic' },
  { id: 'edm74', title: 'Scary Monsters', artist: 'Skrillex', ytId: 'WSeNSzJ2-Jw', genre: 'electronic' },
  { id: 'edm75', title: 'This Is What You Came For', artist: 'Calvin Harris ft. Rihanna', ytId: 'kOkQ4T5WO9E', genre: 'electronic' },
  { id: 'edm76', title: 'Summer', artist: 'Calvin Harris', ytId: 'ebXbLfLACGM', genre: 'electronic' },
  { id: 'edm77', title: 'Feel So Close', artist: 'Calvin Harris', ytId: 'dGghkjpNCQ8', genre: 'electronic' },
  { id: 'edm78', title: 'How Deep Is Your Love', artist: 'Calvin Harris & Disciples', ytId: 'EgqUJOudrcM', genre: 'electronic' },
  { id: 'edm79', title: 'Outside', artist: 'Calvin Harris ft. Ellie Goulding', ytId: 'J9NQFACZYEU', genre: 'electronic' },
  { id: 'edm80', title: 'Sweet Nothing', artist: 'Calvin Harris ft. Florence', ytId: '17ozSeGw-fY', genre: 'electronic' },
  { id: 'edm81', title: 'Roses', artist: 'SAINt JHN (Imanbek Remix)', ytId: 'ele2DMU49Jk', genre: 'electronic' },
  { id: 'edm82', title: 'Runaway (U & I)', artist: 'Galantis', ytId: '5XR7naZ_zZA', genre: 'electronic' },
  { id: 'edm83', title: 'No Money', artist: 'Galantis', ytId: 'xUVz4nRmxn4', genre: 'electronic' },
  { id: 'edm84', title: 'Get Lucky', artist: 'Daft Punk ft. Pharrell', ytId: '5NV6Rdv1a3I', genre: 'electronic' },
  { id: 'edm85', title: 'One More Time', artist: 'Daft Punk', ytId: 'FGBhQbmPwH8', genre: 'electronic' },
  { id: 'edm86', title: 'Harder Better Faster', artist: 'Daft Punk', ytId: 'gAjR4_CbPpQ', genre: 'electronic' },
  { id: 'edm87', title: 'Around The World', artist: 'Daft Punk', ytId: 'dwDns8x3Jb4', genre: 'electronic' },
  { id: 'edm88', title: 'Digital Love', artist: 'Daft Punk', ytId: 'QOngRDVtEQI', genre: 'electronic' },
  { id: 'edm89', title: 'Strobe', artist: 'Deadmau5', ytId: 'tKi9Z-f6qX4', genre: 'electronic' },
  { id: 'edm90', title: 'Ghosts N Stuff', artist: 'Deadmau5', ytId: 'h7ArUgxtlJs', genre: 'electronic' },
  { id: 'edm91', title: 'I Remember', artist: 'Deadmau5 & Kaskade', ytId: 'zK1mLIeXwsQ', genre: 'electronic' },
  { id: 'edm92', title: 'Language', artist: 'Porter Robinson', ytId: '5LILChvqUo4', genre: 'electronic' },
  { id: 'edm93', title: 'Shelter', artist: 'Porter Robinson & Madeon', ytId: 'fzQ6gRAEoy0', genre: 'electronic' },
  { id: 'edm94', title: 'Clarity', artist: 'Zedd ft. Foxes', ytId: 'IxxstCcJlsc', genre: 'electronic' },
  { id: 'edm95', title: 'Stay The Night', artist: 'Zedd ft. Hayley Williams', ytId: 'i-gyZ35074k', genre: 'electronic' },
  { id: 'edm96', title: 'The Middle', artist: 'Zedd ft. Maren Morris', ytId: 'M3mJkSqZbX4', genre: 'electronic' },
  { id: 'edm97', title: 'Beautiful Now', artist: 'Zedd ft. Jon Bellion', ytId: 'n1WpP7iowLc', genre: 'electronic' },

  // ===================== LATIN (100+) =====================
  // Bad Bunny
  { id: 'latin1', title: 'Dakiti', artist: 'Bad Bunny & Jhay Cortez', ytId: 'TmKh7lAwnBI', genre: 'latin' },
  { id: 'latin2', title: 'Callaita', artist: 'Bad Bunny', ytId: 'FxlFmKnfgzs', genre: 'latin' },
  { id: 'latin3', title: 'Me Porto Bonito', artist: 'Bad Bunny & Chencho', ytId: 'fOxnSIUJ64c', genre: 'latin' },
  { id: 'latin4', title: 'Efecto', artist: 'Bad Bunny', ytId: 'XcJxGLdFb_I', genre: 'latin' },
  { id: 'latin5', title: 'Titi Me Pregunto', artist: 'Bad Bunny', ytId: 'gzwB0UT29Ms', genre: 'latin' },
  { id: 'latin6', title: 'Yonaguni', artist: 'Bad Bunny', ytId: 'doLMt10ytHY', genre: 'latin' },
  { id: 'latin7', title: 'Vete', artist: 'Bad Bunny', ytId: 'z_bBqP4R2_o', genre: 'latin' },
  { id: 'latin8', title: 'Mia', artist: 'Bad Bunny ft. Drake', ytId: 'OSUxrSe5pHE', genre: 'latin' },
  { id: 'latin9', title: 'Soy Peor', artist: 'Bad Bunny', ytId: 'c5bjfrz0t_g', genre: 'latin' },
  { id: 'latin10', title: 'Moscow Mule', artist: 'Bad Bunny', ytId: 'bKlsjbv1Qao', genre: 'latin' },
  { id: 'latin11', title: 'Ojitos Lindos', artist: 'Bad Bunny ft. Bomba Estereo', ytId: 'cjrMS4LZsng', genre: 'latin' },
  { id: 'latin12', title: 'La Noche de Anoche', artist: 'Bad Bunny & Rosalia', ytId: 'Xq7bhdfiPuo', genre: 'latin' },
  // J Balvin
  { id: 'latin15', title: 'Mi Gente', artist: 'J Balvin & Willy William', ytId: 'wnJ6LuUFpMo', genre: 'latin' },
  { id: 'latin16', title: 'Ginza', artist: 'J Balvin', ytId: 'iPnNKMxnPB4', genre: 'latin' },
  { id: 'latin17', title: 'Ay Vamos', artist: 'J Balvin', ytId: 'MagXlo6TRC4', genre: 'latin' },
  { id: 'latin18', title: '6 AM', artist: 'J Balvin ft. Farruko', ytId: '4I3CSZRSNTI', genre: 'latin' },
  { id: 'latin19', title: 'Ambiente', artist: 'J Balvin', ytId: 'N3x5rw0LVZY', genre: 'latin' },
  { id: 'latin20', title: 'Safari', artist: 'J Balvin ft. Pharrell', ytId: 'ec2qrsAhcFg', genre: 'latin' },
  { id: 'latin21', title: 'La Cancion', artist: 'J Balvin & Bad Bunny', ytId: '18nCOxQ-ons', genre: 'latin' },
  { id: 'latin22', title: 'In Da Getto', artist: 'J Balvin & Skrillex', ytId: 'RlLH7ST8ER0', genre: 'latin' },
  { id: 'latin23', title: 'Bobo', artist: 'J Balvin', ytId: 'iXRAWKrUuEs', genre: 'latin' },
  // Daddy Yankee
  { id: 'latin25', title: 'Gasolina', artist: 'Daddy Yankee', ytId: 'CCF1_jI8Prk', genre: 'latin' },
  { id: 'latin26', title: 'Despacito', artist: 'Luis Fonsi ft. Daddy Yankee', ytId: 'kJQP7kiw5Fk', genre: 'latin' },
  { id: 'latin27', title: 'Con Calma', artist: 'Daddy Yankee', ytId: 'DiItGE3eAyQ', genre: 'latin' },
  { id: 'latin28', title: 'Dura', artist: 'Daddy Yankee', ytId: 'f24xgPSaXr0', genre: 'latin' },
  { id: 'latin29', title: 'Shaky Shaky', artist: 'Daddy Yankee', ytId: 'aKuivabiOns', genre: 'latin' },
  { id: 'latin30', title: 'Limbo', artist: 'Daddy Yankee', ytId: '6BTjG-dhf5s', genre: 'latin' },
  { id: 'latin31', title: 'Rompe', artist: 'Daddy Yankee', ytId: 'dsgPTrDHOQQ', genre: 'latin' },
  { id: 'latin32', title: 'Lo Que Paso Paso', artist: 'Daddy Yankee', ytId: 'fKPP45zcl14', genre: 'latin' },
  // More Latin
  { id: 'latin35', title: 'Tusa', artist: 'Karol G & Nicki Minaj', ytId: 'tbneQDc-II4', genre: 'latin' },
  { id: 'latin36', title: 'Provenza', artist: 'Karol G', ytId: 'qvqQG19Z8OI', genre: 'latin' },
  { id: 'latin37', title: 'Bichota', artist: 'Karol G', ytId: 'NxxjLD2pFBg', genre: 'latin' },
  { id: 'latin38', title: 'TQG', artist: 'Karol G & Shakira', ytId: 'JNvVJxIUWNQ', genre: 'latin' },
  { id: 'latin39', title: 'Hawái', artist: 'Maluma', ytId: 'eMP-g5ms2Mo', genre: 'latin' },
  { id: 'latin40', title: 'Felices Los 4', artist: 'Maluma', ytId: 'ELMbJnHl-Kk', genre: 'latin' },
  { id: 'latin41', title: 'Chantaje', artist: 'Shakira ft. Maluma', ytId: '6Mgqbai3fKo', genre: 'latin' },
  { id: 'latin42', title: 'La Tortura', artist: 'Shakira ft. Alejandro Sanz', ytId: 'Dsp_8Lm1eSk', genre: 'latin' },
  { id: 'latin43', title: 'Hips Dont Lie', artist: 'Shakira ft. Wyclef Jean', ytId: 'DUT5rEU6pqM', genre: 'latin' },
  { id: 'latin44', title: 'Waka Waka', artist: 'Shakira', ytId: 'pRpeEdMmmQ0', genre: 'latin' },
  { id: 'latin45', title: 'Whenever Wherever', artist: 'Shakira', ytId: 'weRHyjj34ZE', genre: 'latin' },
  { id: 'latin46', title: 'Bzrp Music Sessions 53', artist: 'Shakira & Bizarrap', ytId: 'CocEMWdc7Ck', genre: 'latin' },
  { id: 'latin47', title: 'Suavemente', artist: 'Elvis Crespo', ytId: 'F03gEzdLa2g', genre: 'latin' },
  { id: 'latin48', title: 'Vivir Mi Vida', artist: 'Marc Anthony', ytId: 'YXnjy5YlDwk', genre: 'latin' },
  { id: 'latin49', title: 'Bailando', artist: 'Enrique Iglesias', ytId: 'NUsoVlDFqZg', genre: 'latin' },
  { id: 'latin50', title: 'Subeme La Radio', artist: 'Enrique Iglesias', ytId: '9sg-A-eS6Ig', genre: 'latin' },
  { id: 'latin51', title: 'X', artist: 'Nicky Jam & J Balvin', ytId: '_I_D_8Z4sJE', genre: 'latin' },
  { id: 'latin52', title: 'El Perdon', artist: 'Nicky Jam & Enrique Iglesias', ytId: 'hXI8RQYC36Q', genre: 'latin' },
  { id: 'latin53', title: 'Reggaeton Lento', artist: 'CNCO', ytId: 'CzL5aGLLTKE', genre: 'latin' },
  { id: 'latin54', title: 'La Bicicleta', artist: 'Shakira & Carlos Vives', ytId: 'RxFQeIniK1w', genre: 'latin' },
  { id: 'latin55', title: 'Corazon Sin Cara', artist: 'Prince Royce', ytId: 'pwsTaiiw2LQ', genre: 'latin' },
  { id: 'latin56', title: 'Darte Un Beso', artist: 'Prince Royce', ytId: 'BNn3gGcOk9w', genre: 'latin' },
  { id: 'latin57', title: 'Obsesion', artist: 'Aventura', ytId: 'aB0xQtXYvJI', genre: 'latin' },
  { id: 'latin58', title: 'Propuesta Indecente', artist: 'Romeo Santos', ytId: 'QFs3PIZb3js', genre: 'latin' },
  { id: 'latin59', title: 'El Farsante', artist: 'Ozuna', ytId: '3nNhAYdL8H8', genre: 'latin' },
  { id: 'latin60', title: 'Se Preparo', artist: 'Ozuna', ytId: 'h3-1lUU8OYc', genre: 'latin' },
  { id: 'latin61', title: 'Te Bote', artist: 'Casper, Nio Garcia, Darell, Bad Bunny, Ozuna, Nicky Jam', ytId: '9jK-NcRmVcw', genre: 'latin' },
  { id: 'latin62', title: 'Mayores', artist: 'Becky G ft. Bad Bunny', ytId: 'GMFewiplIbw', genre: 'latin' },
  { id: 'latin63', title: 'Sin Pijama', artist: 'Becky G & Natti Natasha', ytId: 'u9pHJvi8Zhs', genre: 'latin' },
  { id: 'latin64', title: 'Criminal', artist: 'Natti Natasha & Ozuna', ytId: 'VKnrFH3dT78', genre: 'latin' },
  { id: 'latin65', title: 'Ella Quiere Beber', artist: 'Anuel AA', ytId: 'Js-lrr0Clgo', genre: 'latin' },
  { id: 'latin66', title: 'China', artist: 'Anuel AA, Daddy Yankee, Karol G, Ozuna, J Balvin', ytId: 'g6ZQBA2ZFKg', genre: 'latin' },
  { id: 'latin67', title: 'Pepas', artist: 'Farruko', ytId: 'xVJQP3K9a_I', genre: 'latin' },

  // ===================== COUNTRY (80+) =====================
  { id: 'country1', title: 'Old Town Road', artist: 'Lil Nas X ft. Billy Ray', ytId: 'w2Ov5jzm3j8', genre: 'country' },
  { id: 'country2', title: 'Body Like A Back Road', artist: 'Sam Hunt', ytId: 'Mdh2p03cRfw', genre: 'country' },
  { id: 'country3', title: 'Meant To Be', artist: 'Bebe Rexha ft. Florida Georgia Line', ytId: 'zDo0H8Fm7d0', genre: 'country' },
  { id: 'country4', title: 'Cruise', artist: 'Florida Georgia Line', ytId: '8PvebsWcpto', genre: 'country' },
  { id: 'country5', title: 'Tennessee Whiskey', artist: 'Chris Stapleton', ytId: '4zAThXFOy2c', genre: 'country' },
  { id: 'country6', title: 'Die A Happy Man', artist: 'Thomas Rhett', ytId: 'w2CELiObPeQ', genre: 'country' },
  { id: 'country7', title: 'Girl Crush', artist: 'Little Big Town', ytId: 'iHj7TRy4K-0', genre: 'country' },
  { id: 'country8', title: 'Drunk On A Plane', artist: 'Dierks Bentley', ytId: 'QBWlpHgmGmM', genre: 'country' },
  { id: 'country9', title: 'Dirt Road Anthem', artist: 'Jason Aldean', ytId: 'WsqZ33ZMnC8', genre: 'country' },
  { id: 'country10', title: 'Before He Cheats', artist: 'Carrie Underwood', ytId: 'WaSy8yy-mr8', genre: 'country' },
  { id: 'country11', title: 'Blown Away', artist: 'Carrie Underwood', ytId: 'p_8Pt0EYFzk', genre: 'country' },
  { id: 'country12', title: 'Need You Now', artist: 'Lady A', ytId: 'eM213aMKTHg', genre: 'country' },
  { id: 'country13', title: 'Take Me Home Country Roads', artist: 'John Denver', ytId: '1vrEljMfXYo', genre: 'country' },
  { id: 'country14', title: 'Jolene', artist: 'Dolly Parton', ytId: 'Ixrje2rXLMA', genre: 'country' },
  { id: 'country15', title: 'Wagon Wheel', artist: 'Darius Rucker', ytId: 'hvKyBcCDOB4', genre: 'country' },
  { id: 'country16', title: 'Humble And Kind', artist: 'Tim McGraw', ytId: 'awzNHuGqoMc', genre: 'country' },
  { id: 'country17', title: 'Live Like You Were Dying', artist: 'Tim McGraw', ytId: 'AXodH0J4MEc', genre: 'country' },
  { id: 'country18', title: 'Speechless', artist: 'Dan + Shay', ytId: 'bLVCv5VmhZA', genre: 'country' },
  { id: 'country19', title: 'Tequila', artist: 'Dan + Shay', ytId: 'ZBkCA17Ihtk', genre: 'country' },
  { id: 'country20', title: 'Famous', artist: 'Mason Ramsey', ytId: 'S4Nn-NVuuYk', genre: 'country' },
  { id: 'country21', title: 'Buy Dirt', artist: 'Jordan Davis ft. Luke Bryan', ytId: 'kSsKvePP6nI', genre: 'country' },
  { id: 'country22', title: 'Fancy Like', artist: 'Walker Hayes', ytId: 'G_zuB-ogIBw', genre: 'country' },
  { id: 'country23', title: 'Forever After All', artist: 'Luke Combs', ytId: 'nQhbkX5WLUE', genre: 'country' },
  { id: 'country24', title: 'Beautiful Crazy', artist: 'Luke Combs', ytId: 'RviOwY0OKyE', genre: 'country' },
  { id: 'country25', title: 'The Bones', artist: 'Maren Morris', ytId: 'Cxj8vSS2ELU', genre: 'country' },
  { id: 'country26', title: 'Whiskey Glasses', artist: 'Morgan Wallen', ytId: 'rOdhJfxj0wU', genre: 'country' },
  { id: 'country27', title: '7 Summers', artist: 'Morgan Wallen', ytId: '5NKHqMRsG8A', genre: 'country' },
  { id: 'country28', title: 'Last Night', artist: 'Morgan Wallen', ytId: 'RGJJb4g2d-U', genre: 'country' },
  { id: 'country29', title: 'Wasted On You', artist: 'Morgan Wallen', ytId: 'jjGtzEOHh7Q', genre: 'country' },
  { id: 'country30', title: 'Chasin You', artist: 'Morgan Wallen', ytId: 'mMqZJQjlAoA', genre: 'country' },
  { id: 'country31', title: 'Fast Car', artist: 'Luke Combs', ytId: 'K0m4X5dv2NU', genre: 'country' },
  { id: 'country32', title: 'One Number Away', artist: 'Luke Combs', ytId: 'u2aWnpbnLHY', genre: 'country' },
  { id: 'country33', title: 'Beer Never Broke My Heart', artist: 'Luke Combs', ytId: 'r_0JjYUe5jo', genre: 'country' },
  { id: 'country34', title: 'She Had Me At Heads Carolina', artist: 'Cole Swindell', ytId: 'oPgcKYFcHPU', genre: 'country' },
  { id: 'country35', title: 'Chillin It', artist: 'Cole Swindell', ytId: '2C8YMNFwHHM', genre: 'country' },
  { id: 'country36', title: 'Anything Goes', artist: 'Florida Georgia Line', ytId: 'bjPqsDU0j2I', genre: 'country' },
  { id: 'country37', title: 'This Is How We Roll', artist: 'Florida Georgia Line ft. Luke Bryan', ytId: 'ovQj2Qor8xQ', genre: 'country' },
  { id: 'country38', title: 'Chicken Fried', artist: 'Zac Brown Band', ytId: 'e4ujS1er1r0', genre: 'country' },
  { id: 'country39', title: 'Knee Deep', artist: 'Zac Brown Band ft. Jimmy Buffett', ytId: 'KaYV7tCjUWE', genre: 'country' },
  { id: 'country40', title: 'Toes', artist: 'Zac Brown Band', ytId: 'jRf2O5nYv1c', genre: 'country' },
  { id: 'country41', title: 'Somethin Bout A Truck', artist: 'Kip Moore', ytId: 'Qu7EE3W6tOY', genre: 'country' },
  { id: 'country42', title: 'Barefoot Blue Jean Night', artist: 'Jake Owen', ytId: 'cJxw5vLsWTs', genre: 'country' },
  { id: 'country43', title: 'My Church', artist: 'Maren Morris', ytId: 'tOrHLPp7bwg', genre: 'country' },
  { id: 'country44', title: 'Middle Of A Memory', artist: 'Cole Swindell', ytId: 'QBHiQgsFbC4', genre: 'country' },
  { id: 'country45', title: 'House Party', artist: 'Sam Hunt', ytId: 'oKVWbSdNK2E', genre: 'country' },
  { id: 'country46', title: 'Take Your Time', artist: 'Sam Hunt', ytId: 'wERBbOu9laM', genre: 'country' },
  { id: 'country47', title: 'Burning House', artist: 'Cam', ytId: '6tLhbC3u7uM', genre: 'country' },
  { id: 'country48', title: 'I Hope', artist: 'Gabby Barrett', ytId: 'c_bYy4kBpJU', genre: 'country' },
  { id: 'country49', title: 'Amarillo By Morning', artist: 'George Strait', ytId: 'iLfTwKA-T-0', genre: 'country' },
  { id: 'country50', title: 'Friends In Low Places', artist: 'Garth Brooks', ytId: 'p0_der_5hRM', genre: 'country' },

  // ===================== K-POP (100+) =====================
  // BTS
  { id: 'kpop1', title: 'Dynamite', artist: 'BTS', ytId: 'gdZLi9oWNZg', genre: 'kpop' },
  { id: 'kpop2', title: 'Butter', artist: 'BTS', ytId: 'WMweEpGlu_U', genre: 'kpop' },
  { id: 'kpop3', title: 'Boy With Luv', artist: 'BTS ft. Halsey', ytId: 'XsX3ATc3FbA', genre: 'kpop' },
  { id: 'kpop4', title: 'DNA', artist: 'BTS', ytId: 'MBdVXkSdhwU', genre: 'kpop' },
  { id: 'kpop5', title: 'Fake Love', artist: 'BTS', ytId: '7C2z4GqqS5E', genre: 'kpop' },
  { id: 'kpop6', title: 'IDOL', artist: 'BTS', ytId: 'pBuZEGYXA6E', genre: 'kpop' },
  { id: 'kpop7', title: 'MIC Drop', artist: 'BTS', ytId: 'kTlv5_Bs8aw', genre: 'kpop' },
  { id: 'kpop8', title: 'Blood Sweat & Tears', artist: 'BTS', ytId: 'hmE9f-TEutc', genre: 'kpop' },
  { id: 'kpop9', title: 'Spring Day', artist: 'BTS', ytId: 'xEeFrLSkMm8', genre: 'kpop' },
  { id: 'kpop10', title: 'Permission To Dance', artist: 'BTS', ytId: 'CuklIb9d3fI', genre: 'kpop' },
  { id: 'kpop11', title: 'Life Goes On', artist: 'BTS', ytId: '-5q5mZbe3V8', genre: 'kpop' },
  { id: 'kpop12', title: 'Fire', artist: 'BTS', ytId: '4ujQOR2DMFM', genre: 'kpop' },
  { id: 'kpop13', title: 'Save ME', artist: 'BTS', ytId: 'GZjt_sA2eso', genre: 'kpop' },
  { id: 'kpop14', title: 'ON', artist: 'BTS', ytId: 'mPVDGOVjRQ0', genre: 'kpop' },
  // BLACKPINK
  { id: 'kpop20', title: 'DDU-DU DDU-DU', artist: 'BLACKPINK', ytId: 'IHNzOHi8sJs', genre: 'kpop' },
  { id: 'kpop21', title: 'Kill This Love', artist: 'BLACKPINK', ytId: '2S24-y0Ij3Y', genre: 'kpop' },
  { id: 'kpop22', title: 'How You Like That', artist: 'BLACKPINK', ytId: 'ioNng23DkIM', genre: 'kpop' },
  { id: 'kpop23', title: 'Lovesick Girls', artist: 'BLACKPINK', ytId: 'dyRsYk0LyA8', genre: 'kpop' },
  { id: 'kpop24', title: 'Pink Venom', artist: 'BLACKPINK', ytId: 'gQlMMD8auMs', genre: 'kpop' },
  { id: 'kpop25', title: 'Shut Down', artist: 'BLACKPINK', ytId: 'POe9SOEKotk', genre: 'kpop' },
  { id: 'kpop26', title: 'Ice Cream', artist: 'BLACKPINK ft. Selena Gomez', ytId: 'vRXZj0DzXIA', genre: 'kpop' },
  { id: 'kpop27', title: 'BOOMBAYAH', artist: 'BLACKPINK', ytId: 'bwmSjveL3Lc', genre: 'kpop' },
  { id: 'kpop28', title: 'As If Its Your Last', artist: 'BLACKPINK', ytId: 'Amq-qlqbjYA', genre: 'kpop' },
  { id: 'kpop29', title: 'Playing With Fire', artist: 'BLACKPINK', ytId: '9pdj4iJD08s', genre: 'kpop' },
  { id: 'kpop30', title: 'Whistle', artist: 'BLACKPINK', ytId: 'dISNgvVpWlo', genre: 'kpop' },
  // Solo Artists
  { id: 'kpop35', title: 'Gangnam Style', artist: 'PSY', ytId: '9bZkp7q19f0', genre: 'kpop' },
  { id: 'kpop36', title: 'Gentleman', artist: 'PSY', ytId: 'ASO_zypdnsQ', genre: 'kpop' },
  { id: 'kpop37', title: 'SOLO', artist: 'Jennie', ytId: 'b73BI9eUkjM', genre: 'kpop' },
  { id: 'kpop38', title: 'On The Ground', artist: 'ROSÉ', ytId: 'CKZvWhCqx1s', genre: 'kpop' },
  { id: 'kpop39', title: 'LALISA', artist: 'LISA', ytId: 'awkkyBH2zEo', genre: 'kpop' },
  { id: 'kpop40', title: 'MONEY', artist: 'LISA', ytId: 'dNCWe_6HAM8', genre: 'kpop' },
  { id: 'kpop41', title: 'FLOWER', artist: 'Jisoo', ytId: 'laGVtHwOuwg', genre: 'kpop' },
  // NewJeans
  { id: 'kpop45', title: 'Super Shy', artist: 'NewJeans', ytId: 'ArmDp-zijuc', genre: 'kpop' },
  { id: 'kpop46', title: 'Hype Boy', artist: 'NewJeans', ytId: '11cta61wi0g', genre: 'kpop' },
  { id: 'kpop47', title: 'Attention', artist: 'NewJeans', ytId: 'js1CtxSY38I', genre: 'kpop' },
  { id: 'kpop48', title: 'OMG', artist: 'NewJeans', ytId: 'sVTy_wmn5SU', genre: 'kpop' },
  { id: 'kpop49', title: 'Ditto', artist: 'NewJeans', ytId: 'pSUydWEqKwE', genre: 'kpop' },
  { id: 'kpop50', title: 'Cookie', artist: 'NewJeans', ytId: 'VOmIplFAGeg', genre: 'kpop' },
  // IVE
  { id: 'kpop55', title: 'Love Dive', artist: 'IVE', ytId: 'Y8JFxS1HlDo', genre: 'kpop' },
  { id: 'kpop56', title: 'After LIKE', artist: 'IVE', ytId: 'F0B7HDiY-10', genre: 'kpop' },
  { id: 'kpop57', title: 'Eleven', artist: 'IVE', ytId: 'zI4M7rltbDU', genre: 'kpop' },
  { id: 'kpop58', title: 'I AM', artist: 'IVE', ytId: '6ZUIwj3FgUY', genre: 'kpop' },
  // LE SSERAFIM
  { id: 'kpop60', title: 'Antifragile', artist: 'LE SSERAFIM', ytId: 'pyf8cbqyfPs', genre: 'kpop' },
  { id: 'kpop61', title: 'FEARLESS', artist: 'LE SSERAFIM', ytId: '4vbDFu0PUew', genre: 'kpop' },
  { id: 'kpop62', title: 'UNFORGIVEN', artist: 'LE SSERAFIM', ytId: 'UBURTj20HXI', genre: 'kpop' },
  { id: 'kpop63', title: 'Eve Psyche & The Bluebeards wife', artist: 'LE SSERAFIM', ytId: 'aZOWAqSPCpE', genre: 'kpop' },
  // aespa
  { id: 'kpop65', title: 'Next Level', artist: 'aespa', ytId: '4TWR90KJl84', genre: 'kpop' },
  { id: 'kpop66', title: 'Savage', artist: 'aespa', ytId: 'WPdWvnAAurg', genre: 'kpop' },
  { id: 'kpop67', title: 'Black Mamba', artist: 'aespa', ytId: 'ZeerrnuLi5E', genre: 'kpop' },
  { id: 'kpop68', title: 'Dreams Come True', artist: 'aespa', ytId: 'cOP_f0pXiV8', genre: 'kpop' },
  { id: 'kpop69', title: 'Supernova', artist: 'aespa', ytId: 'phuiiNCxRMg', genre: 'kpop' },
  // SEVENTEEN
  { id: 'kpop70', title: 'God of Music', artist: 'SEVENTEEN', ytId: 'W-VGiE9rKMs', genre: 'kpop' },
  { id: 'kpop71', title: 'Super', artist: 'SEVENTEEN', ytId: 'x1QoGsXRrZE', genre: 'kpop' },
  { id: 'kpop72', title: 'Very Nice', artist: 'SEVENTEEN', ytId: 'J-wFp43XOrA', genre: 'kpop' },
  { id: 'kpop73', title: 'Dont Wanna Cry', artist: 'SEVENTEEN', ytId: 'zEkg4GBQumc', genre: 'kpop' },
  // Stray Kids
  { id: 'kpop75', title: 'MANIAC', artist: 'Stray Kids', ytId: 'OvioeS1ZZ7o', genre: 'kpop' },
  { id: 'kpop76', title: 'God's Menu', artist: 'Stray Kids', ytId: 'TQTlCHxyuu8', genre: 'kpop' },
  { id: 'kpop77', title: 'Back Door', artist: 'Stray Kids', ytId: 'X-uJtV8ScYk', genre: 'kpop' },
  { id: 'kpop78', title: 'Thunderous', artist: 'Stray Kids', ytId: 'EaswWiwMVs8', genre: 'kpop' },
  { id: 'kpop79', title: 'S-Class', artist: 'Stray Kids', ytId: 'YkPqh1_i_u0', genre: 'kpop' },
  // TWICE
  { id: 'kpop80', title: 'What Is Love', artist: 'TWICE', ytId: 'i0p1bmr0EmE', genre: 'kpop' },
  { id: 'kpop81', title: 'TT', artist: 'TWICE', ytId: 'ePpPVE-GGJw', genre: 'kpop' },
  { id: 'kpop82', title: 'Fancy', artist: 'TWICE', ytId: 'kOHB85vDuow', genre: 'kpop' },
  { id: 'kpop83', title: 'Feel Special', artist: 'TWICE', ytId: '3ymwOvzhwHs', genre: 'kpop' },
  { id: 'kpop84', title: 'Yes or Yes', artist: 'TWICE', ytId: 'mAKsZ26SabQ', genre: 'kpop' },
  // More
  { id: 'kpop85', title: 'Any Song', artist: 'Zico', ytId: 'UuV2BmJ1p_I', genre: 'kpop' },
  { id: 'kpop86', title: 'LATATA', artist: '(G)I-DLE', ytId: '9mQk7Evt6Vs', genre: 'kpop' },
  { id: 'kpop87', title: 'Queencard', artist: '(G)I-DLE', ytId: '7HDeem-JaSY', genre: 'kpop' },
  { id: 'kpop88', title: 'Tomboy', artist: '(G)I-DLE', ytId: 'Jh4QFaPmdss', genre: 'kpop' },
  { id: 'kpop89', title: 'Panorama', artist: 'IZ*ONE', ytId: 'G8GaQdW2wHc', genre: 'kpop' },
  { id: 'kpop90', title: 'La Vie En Rose', artist: 'IZ*ONE', ytId: 'WZwr2a_lFWY', genre: 'kpop' },
  { id: 'kpop91', title: 'WANNABE', artist: 'ITZY', ytId: 'fE2h3lGlOsk', genre: 'kpop' },
  { id: 'kpop92', title: 'DALLA DALLA', artist: 'ITZY', ytId: 'pNfTK39k55U', genre: 'kpop' },
  { id: 'kpop93', title: 'Cheer Up', artist: 'TWICE', ytId: 'c7rCyll5AeY', genre: 'kpop' },

  // ===================== INDIE / ALTERNATIVE (80+) =====================
  { id: 'indie1', title: 'Sweater Weather', artist: 'The Neighbourhood', ytId: 'GCdwKhTtNNw', genre: 'indie' },
  { id: 'indie2', title: 'Afraid', artist: 'The Neighbourhood', ytId: 'LrWwtU7iyl0', genre: 'indie' },
  { id: 'indie3', title: 'Heather', artist: 'Conan Gray', ytId: 'GPUg7n8-M6o', genre: 'indie' },
  { id: 'indie4', title: 'Maniac', artist: 'Conan Gray', ytId: 'BqnG_Ei35JE', genre: 'indie' },
  { id: 'indie5', title: 'Wish You Were Sober', artist: 'Conan Gray', ytId: 'xwz2Jc_gwkM', genre: 'indie' },
  { id: 'indie6', title: 'Electric Love', artist: 'BØRNS', ytId: 'RYr96YYEaZY', genre: 'indie' },
  { id: 'indie7', title: 'Take Me To Church', artist: 'Hozier', ytId: 'PVjiKRfKpPI', genre: 'indie' },
  { id: 'indie8', title: 'Too Sweet', artist: 'Hozier', ytId: 'KrD15BCHIOY', genre: 'indie' },
  { id: 'indie9', title: 'Work Song', artist: 'Hozier', ytId: 'nH7bjV0Q_44', genre: 'indie' },
  { id: 'indie10', title: 'Someone New', artist: 'Hozier', ytId: 'bPJSsAr2iu0', genre: 'indie' },
  { id: 'indie11', title: 'Cigarette Daydreams', artist: 'Cage The Elephant', ytId: 'opeETnB8m8w', genre: 'indie' },
  { id: 'indie12', title: 'Aint No Rest For The Wicked', artist: 'Cage The Elephant', ytId: 'HKtsdZs9LJo', genre: 'indie' },
  { id: 'indie13', title: 'Trouble', artist: 'Cage The Elephant', ytId: 'lA-gGl6qihQ', genre: 'indie' },
  { id: 'indie14', title: 'Do I Wanna Know', artist: 'Arctic Monkeys', ytId: 'bpOSxM0rNPM', genre: 'indie' },
  { id: 'indie15', title: 'R U Mine', artist: 'Arctic Monkeys', ytId: 'ngzC_8zqInk', genre: 'indie' },
  { id: 'indie16', title: '505', artist: 'Arctic Monkeys', ytId: 'MrmPDUvKyLs', genre: 'indie' },
  { id: 'indie17', title: 'I Wanna Be Yours', artist: 'Arctic Monkeys', ytId: 'nyuo9-OjNNg', genre: 'indie' },
  { id: 'indie18', title: 'Why Do You Only Call Me When Youre High', artist: 'Arctic Monkeys', ytId: '6366dxFf-Os', genre: 'indie' },
  { id: 'indie19', title: 'Fluorescent Adolescent', artist: 'Arctic Monkeys', ytId: 'ma9I9VBKPiw', genre: 'indie' },
  { id: 'indie20', title: 'Snap Out Of It', artist: 'Arctic Monkeys', ytId: 'H8tLS_NOWLs', genre: 'indie' },
  { id: 'indie21', title: 'Pumped Up Kicks', artist: 'Foster The People', ytId: 'SDTZ7iX4vTQ', genre: 'indie' },
  { id: 'indie22', title: 'Sit Next To Me', artist: 'Foster The People', ytId: 'BKLVpDTZOPQ', genre: 'indie' },
  { id: 'indie23', title: 'Little Talks', artist: 'Of Monsters and Men', ytId: 'ghb6eDopW8I', genre: 'indie' },
  { id: 'indie24', title: 'Mountain Sound', artist: 'Of Monsters and Men', ytId: 'qt7ox1M_XG4', genre: 'indie' },
  { id: 'indie25', title: 'Ho Hey', artist: 'The Lumineers', ytId: 'zvCBSSwgtg4', genre: 'indie' },
  { id: 'indie26', title: 'Ophelia', artist: 'The Lumineers', ytId: 'pTOC_q0NLTk', genre: 'indie' },
  { id: 'indie27', title: 'Stubborn Love', artist: 'The Lumineers', ytId: 'UJWk_KNbDHo', genre: 'indie' },
  { id: 'indie28', title: 'Cleopatra', artist: 'The Lumineers', ytId: 'aN5s9N_pTUs', genre: 'indie' },
  { id: 'indie29', title: 'Home', artist: 'Edward Sharpe', ytId: 'DHEOF_rcND8', genre: 'indie' },
  { id: 'indie30', title: 'Riptide', artist: 'Vance Joy', ytId: 'uJ_1HMAGb4k', genre: 'indie' },
  { id: 'indie31', title: 'Georgia', artist: 'Vance Joy', ytId: 'ULEsNgVH1UE', genre: 'indie' },
  { id: 'indie32', title: 'Youth', artist: 'Troye Sivan', ytId: 'XYAghEq5Lfw', genre: 'indie' },
  { id: 'indie33', title: 'BITE', artist: 'Troye Sivan', ytId: 'qWB0cVy5yhg', genre: 'indie' },
  { id: 'indie34', title: 'Angel Baby', artist: 'Troye Sivan', ytId: 'hLQi3P4VDuk', genre: 'indie' },
  { id: 'indie35', title: 'Rush', artist: 'Troye Sivan', ytId: '8v_4O44sfjM', genre: 'indie' },
  { id: 'indie36', title: 'Blue Monday', artist: 'New Order', ytId: 'FYH8DsU2WCk', genre: 'indie' },
  { id: 'indie37', title: 'Somebody Else', artist: 'The 1975', ytId: 'Bimd2nZirT4', genre: 'indie' },
  { id: 'indie38', title: 'Chocolate', artist: 'The 1975', ytId: 'CHk5SWVO4p8', genre: 'indie' },
  { id: 'indie39', title: 'Robbers', artist: 'The 1975', ytId: 'Iyy3YOpxL2k', genre: 'indie' },
  { id: 'indie40', title: 'About You', artist: 'The 1975', ytId: 'JGHQwxqPuH4', genre: 'indie' },
  { id: 'indie41', title: 'The Sound', artist: 'The 1975', ytId: 'FSnAllHtG70', genre: 'indie' },
  { id: 'indie42', title: 'ILYSB', artist: 'LANY', ytId: '-6Zr0LrQ2Qw', genre: 'indie' },
  { id: 'indie43', title: 'Malibu Nights', artist: 'LANY', ytId: 'bp-xWBfnXRA', genre: 'indie' },
  { id: 'indie44', title: 'Closer', artist: 'Tegan and Sara', ytId: '9e9NSMY8QiQ', genre: 'indie' },
  { id: 'indie45', title: 'Skinny Love', artist: 'Bon Iver', ytId: 'ssdgFoHLwnk', genre: 'indie' },
  { id: 'indie46', title: 'Holocene', artist: 'Bon Iver', ytId: 'TWcyIpul8OE', genre: 'indie' },
  { id: 'indie47', title: 'Ribs', artist: 'Lorde', ytId: '4qaeoz_7cyE', genre: 'indie' },
  { id: 'indie48', title: 'Green Light', artist: 'Lorde', ytId: 'dMK_npDG12Q', genre: 'indie' },
  { id: 'indie49', title: 'Royals', artist: 'Lorde', ytId: 'nlcIKh6sBtc', genre: 'indie' },
  { id: 'indie50', title: 'Team', artist: 'Lorde', ytId: 'f2JuxM-snGc', genre: 'indie' },
  { id: 'indie51', title: 'Liability', artist: 'Lorde', ytId: 'BtvJaNeELic', genre: 'indie' },
  { id: 'indie52', title: 'Francis Forever', artist: 'Mitski', ytId: 'UMJm_97QXHA', genre: 'indie' },
  { id: 'indie53', title: 'First Love Late Spring', artist: 'Mitski', ytId: 'WCphVn7fe1g', genre: 'indie' },
  { id: 'indie54', title: 'Washing Machine Heart', artist: 'Mitski', ytId: 'aM_v0lv_Kv4', genre: 'indie' },
  { id: 'indie55', title: 'Nobody', artist: 'Mitski', ytId: 'qooWnw5rEcI', genre: 'indie' },
  { id: 'indie56', title: 'My Love Mine All Mine', artist: 'Mitski', ytId: 'lO1nBCo4aK4', genre: 'indie' },
  { id: 'indie57', title: 'Motion Sickness', artist: 'Phoebe Bridgers', ytId: 'WJvmwK3jFMk', genre: 'indie' },
  { id: 'indie58', title: 'Kyoto', artist: 'Phoebe Bridgers', ytId: 'Tw0zYd0eIlk', genre: 'indie' },
  { id: 'indie59', title: 'I Know The End', artist: 'Phoebe Bridgers', ytId: 'WJ9-xN6dCW4', genre: 'indie' },
  { id: 'indie60', title: 'The Night We Met', artist: 'Lord Huron', ytId: 'KtlgYxa6BMU', genre: 'indie' },
  { id: 'indie61', title: 'Love Like Ghosts', artist: 'Lord Huron', ytId: 'bHse2E9Rj0w', genre: 'indie' },
  { id: 'indie62', title: 'Space Song', artist: 'Beach House', ytId: 'RBtlPT23PTM', genre: 'indie' },
  { id: 'indie63', title: 'Myth', artist: 'Beach House', ytId: 'FuvWc3ToDHg', genre: 'indie' },
  { id: 'indie64', title: 'Dreams', artist: 'Fleetwood Mac', ytId: 'mrZRURcb1cM', genre: 'indie' },
  { id: 'indie65', title: 'The Chain', artist: 'Fleetwood Mac', ytId: 'JDG2m5hN1vo', genre: 'indie' },
  { id: 'indie66', title: 'Everywhere', artist: 'Fleetwood Mac', ytId: 'YF1R0hc5Q2I', genre: 'indie' },

  // ===================== METAL (60+) =====================
  // Metallica
  { id: 'metal1', title: 'Enter Sandman', artist: 'Metallica', ytId: 'CD-E-LDc384', genre: 'metal' },
  { id: 'metal2', title: 'Nothing Else Matters', artist: 'Metallica', ytId: 'tAGnKpE4NCI', genre: 'metal' },
  { id: 'metal3', title: 'One', artist: 'Metallica', ytId: 'WM8bTdBs-cw', genre: 'metal' },
  { id: 'metal4', title: 'Master of Puppets', artist: 'Metallica', ytId: 'E0ozmU9cJDg', genre: 'metal' },
  { id: 'metal5', title: 'For Whom The Bell Tolls', artist: 'Metallica', ytId: 'eeqGuaAl6Ic', genre: 'metal' },
  { id: 'metal6', title: 'Fade To Black', artist: 'Metallica', ytId: 'WEQnzs8wl6E', genre: 'metal' },
  { id: 'metal7', title: 'Wherever I May Roam', artist: 'Metallica', ytId: 'EuIol63oAmI', genre: 'metal' },
  { id: 'metal8', title: 'The Unforgiven', artist: 'Metallica', ytId: 'Ckom3gf57Yw', genre: 'metal' },
  { id: 'metal9', title: 'Sad But True', artist: 'Metallica', ytId: 'A8MO7fkZc5o', genre: 'metal' },
  { id: 'metal10', title: 'Seek & Destroy', artist: 'Metallica', ytId: 'NUAdgt5Glk0', genre: 'metal' },
  // System of a Down
  { id: 'metal15', title: 'Chop Suey', artist: 'System of a Down', ytId: 'CSvFpBOe8eY', genre: 'metal' },
  { id: 'metal16', title: 'Toxicity', artist: 'System of a Down', ytId: 'iywaBOMvYLI', genre: 'metal' },
  { id: 'metal17', title: 'B.Y.O.B', artist: 'System of a Down', ytId: 'zUzd9KyIDrM', genre: 'metal' },
  { id: 'metal18', title: 'Aerials', artist: 'System of a Down', ytId: 'L-iepu3EtyE', genre: 'metal' },
  { id: 'metal19', title: 'Sugar', artist: 'System of a Down', ytId: '5vBGOrI6yBk', genre: 'metal' },
  { id: 'metal20', title: 'Lonely Day', artist: 'System of a Down', ytId: 'DnGdoEa1tPg', genre: 'metal' },
  // Linkin Park
  { id: 'metal25', title: 'Numb', artist: 'Linkin Park', ytId: 'kXYiU_JCYtU', genre: 'metal' },
  { id: 'metal26', title: 'In The End', artist: 'Linkin Park', ytId: 'eVTXPUF4Oz4', genre: 'metal' },
  { id: 'metal27', title: 'Crawling', artist: 'Linkin Park', ytId: 'Gd9OhYroLN0', genre: 'metal' },
  { id: 'metal28', title: 'Faint', artist: 'Linkin Park', ytId: 'LYU-8IFcDPw', genre: 'metal' },
  { id: 'metal29', title: 'Breaking The Habit', artist: 'Linkin Park', ytId: 'v2H4l9RpkwM', genre: 'metal' },
  { id: 'metal30', title: 'What Ive Done', artist: 'Linkin Park', ytId: '8sgycukafqQ', genre: 'metal' },
  { id: 'metal31', title: 'Somewhere I Belong', artist: 'Linkin Park', ytId: 'zsCD5XCu6CM', genre: 'metal' },
  { id: 'metal32', title: 'One Step Closer', artist: 'Linkin Park', ytId: '4qlCC1GOwFw', genre: 'metal' },
  { id: 'metal33', title: 'Papercut', artist: 'Linkin Park', ytId: 'vjVkXlxsO8Q', genre: 'metal' },
  { id: 'metal34', title: 'New Divide', artist: 'Linkin Park', ytId: 'ysSxxIqKNN0', genre: 'metal' },
  // Foo Fighters
  { id: 'metal40', title: 'The Pretender', artist: 'Foo Fighters', ytId: 'SBjQ9tuuTJQ', genre: 'metal' },
  { id: 'metal41', title: 'Everlong', artist: 'Foo Fighters', ytId: 'eBG7P-K-r1Y', genre: 'metal' },
  { id: 'metal42', title: 'Best of You', artist: 'Foo Fighters', ytId: 'h_L4Rixya64', genre: 'metal' },
  { id: 'metal43', title: 'Learn To Fly', artist: 'Foo Fighters', ytId: '1VQ_3sBZEm0', genre: 'metal' },
  { id: 'metal44', title: 'My Hero', artist: 'Foo Fighters', ytId: 'EqWRaAF6_WY', genre: 'metal' },
  { id: 'metal45', title: 'Monkey Wrench', artist: 'Foo Fighters', ytId: 'I7rCNiiNPxA', genre: 'metal' },
  // Iron Maiden
  { id: 'metal50', title: 'The Trooper', artist: 'Iron Maiden', ytId: '2G5rfPISIwo', genre: 'metal' },
  { id: 'metal51', title: 'Run To The Hills', artist: 'Iron Maiden', ytId: '86URGgqONvA', genre: 'metal' },
  { id: 'metal52', title: 'Fear Of The Dark', artist: 'Iron Maiden', ytId: 'Nba3Tr_GLZU', genre: 'metal' },
  { id: 'metal53', title: 'Hallowed Be Thy Name', artist: 'Iron Maiden', ytId: 'G90ngH2anxQ', genre: 'metal' },
  { id: 'metal54', title: 'Number Of The Beast', artist: 'Iron Maiden', ytId: 'WxnN05vOuSM', genre: 'metal' },
  // More Metal
  { id: 'metal55', title: 'Crazy Train', artist: 'Ozzy Osbourne', ytId: 'tMDFv5m18Pw', genre: 'metal' },
  { id: 'metal56', title: 'Paranoid', artist: 'Black Sabbath', ytId: '0qanF-91aJo', genre: 'metal' },
  { id: 'metal57', title: 'Iron Man', artist: 'Black Sabbath', ytId: '5s7_WbiR79E', genre: 'metal' },
  { id: 'metal58', title: 'War Pigs', artist: 'Black Sabbath', ytId: 'LQUXuQ6Zd9w', genre: 'metal' },
  { id: 'metal59', title: 'Breaking The Law', artist: 'Judas Priest', ytId: 'L397TWLwrUU', genre: 'metal' },
  { id: 'metal60', title: 'Painkiller', artist: 'Judas Priest', ytId: 'nM__lPTWThU', genre: 'metal' },
  { id: 'metal61', title: 'Raining Blood', artist: 'Slayer', ytId: 'z8ZqFlw6hYg', genre: 'metal' },
  { id: 'metal62', title: 'Walk', artist: 'Pantera', ytId: 'AkFqg5wAuFk', genre: 'metal' },
  { id: 'metal63', title: 'Cowboys From Hell', artist: 'Pantera', ytId: '2DfYLar2QGI', genre: 'metal' },
  { id: 'metal64', title: 'Afterlife', artist: 'Avenged Sevenfold', ytId: 'HIRNdveLnJI', genre: 'metal' },
  { id: 'metal65', title: 'Bat Country', artist: 'Avenged Sevenfold', ytId: 'IHS3qJdxefY', genre: 'metal' },
  { id: 'metal66', title: 'So Far Away', artist: 'Avenged Sevenfold', ytId: 'A7ry4cx6HfY', genre: 'metal' },
  { id: 'metal67', title: 'Hail To The King', artist: 'Avenged Sevenfold', ytId: 'DelhLppPSxY', genre: 'metal' },
  { id: 'metal68', title: 'Before I Forget', artist: 'Slipknot', ytId: 'qw2LU1yS7aw', genre: 'metal' },
  { id: 'metal69', title: 'Psychosocial', artist: 'Slipknot', ytId: '5abamRO41fE', genre: 'metal' },
  { id: 'metal70', title: 'Duality', artist: 'Slipknot', ytId: '6fVE8kSM43I', genre: 'metal' },

  // ===================== REGGAE (40+) =====================
  { id: 'reggae1', title: 'One Love', artist: 'Bob Marley', ytId: 'vdB-8eLEW8g', genre: 'reggae' },
  { id: 'reggae2', title: 'No Woman No Cry', artist: 'Bob Marley', ytId: 'IT8XvzIfi4s', genre: 'reggae' },
  { id: 'reggae3', title: 'Three Little Birds', artist: 'Bob Marley', ytId: 'zaGUr6wzyT8', genre: 'reggae' },
  { id: 'reggae4', title: 'Is This Love', artist: 'Bob Marley', ytId: 'CHekNnySAfM', genre: 'reggae' },
  { id: 'reggae5', title: 'Redemption Song', artist: 'Bob Marley', ytId: 'yv5xonFSC4c', genre: 'reggae' },
  { id: 'reggae6', title: 'Buffalo Soldier', artist: 'Bob Marley', ytId: 'S5FCdx7Dn0o', genre: 'reggae' },
  { id: 'reggae7', title: 'Could You Be Loved', artist: 'Bob Marley', ytId: 'g3t6YDnGXAc', genre: 'reggae' },
  { id: 'reggae8', title: 'Jamming', artist: 'Bob Marley', ytId: 'oFRbZJXjWIA', genre: 'reggae' },
  { id: 'reggae9', title: 'Stir It Up', artist: 'Bob Marley', ytId: 'F_ENWBaW-TI', genre: 'reggae' },
  { id: 'reggae10', title: 'Get Up Stand Up', artist: 'Bob Marley', ytId: 'F693lcLQjOo', genre: 'reggae' },
  { id: 'reggae11', title: 'I Shot The Sheriff', artist: 'Bob Marley', ytId: 'APVXjDYrFpg', genre: 'reggae' },
  { id: 'reggae12', title: 'Waiting In Vain', artist: 'Bob Marley', ytId: 'jB32LzLrLik', genre: 'reggae' },
  { id: 'reggae13', title: 'Sun Is Shining', artist: 'Bob Marley', ytId: 'vdCPn5K4d-M', genre: 'reggae' },
  { id: 'reggae14', title: 'Exodus', artist: 'Bob Marley', ytId: 'A85dHekb0g0', genre: 'reggae' },
  { id: 'reggae15', title: 'Iron Lion Zion', artist: 'Bob Marley', ytId: 'YTT4yKYbQPY', genre: 'reggae' },
  { id: 'reggae16', title: 'Electric Avenue', artist: 'Eddy Grant', ytId: 'IuwxZSIS__4', genre: 'reggae' },
  { id: 'reggae17', title: 'Red Red Wine', artist: 'UB40', ytId: 'zXt56MB-3vc', genre: 'reggae' },
  { id: 'reggae18', title: 'Kingston Town', artist: 'UB40', ytId: 'VX5PPCfZ88M', genre: 'reggae' },
  { id: 'reggae19', title: 'Here Comes The Hotstepper', artist: 'Ini Kamoze', ytId: 'eEJ2b6IaGWU', genre: 'reggae' },
  { id: 'reggae20', title: 'Pass The Dutchie', artist: 'Musical Youth', ytId: 'dFtLONl4cNc', genre: 'reggae' },
  { id: 'reggae21', title: 'Welcome To Jamrock', artist: 'Damian Marley', ytId: 'bQ-0_VpfExU', genre: 'reggae' },
  { id: 'reggae22', title: 'Road To Zion', artist: 'Damian Marley ft. Nas', ytId: 'j9ChMjzQ5IA', genre: 'reggae' },
  { id: 'reggae23', title: 'Sweat', artist: 'Inner Circle', ytId: 'Y_-RGE3RCz4', genre: 'reggae' },
  { id: 'reggae24', title: 'Murder She Wrote', artist: 'Chaka Demus & Pliers', ytId: '8jyoP4Xq5js', genre: 'reggae' },
  { id: 'reggae25', title: 'Informer', artist: 'Snow', ytId: 'TSffz_bl6zo', genre: 'reggae' },
  { id: 'reggae26', title: '007 Shanty Town', artist: 'Desmond Dekker', ytId: 'bP8NiCcJLLM', genre: 'reggae' },
  { id: 'reggae27', title: 'Israelites', artist: 'Desmond Dekker', ytId: 'dvzb-lYtgBA', genre: 'reggae' },
  { id: 'reggae28', title: 'Rivers of Babylon', artist: 'Boney M', ytId: 'ta42xU2UXLA', genre: 'reggae' },
  { id: 'reggae29', title: 'Pressure Drop', artist: 'Toots and The Maytals', ytId: '6rb13ksYO0s', genre: 'reggae' },
  { id: 'reggae30', title: '54-46 Thats My Number', artist: 'Toots and The Maytals', ytId: 'mzR_lTZCPlk', genre: 'reggae' },

  // ===================== AFROBEATS (50+) =====================
  { id: 'afro1', title: 'Essence', artist: 'Wizkid ft. Tems', ytId: 'GePq8s3vrlM', genre: 'afrobeats' },
  { id: 'afro2', title: 'Joro', artist: 'Wizkid', ytId: 'Zdqxwo9qwx8', genre: 'afrobeats' },
  { id: 'afro3', title: 'Come Closer', artist: 'Wizkid ft. Drake', ytId: '4Hj40pP2Zzs', genre: 'afrobeats' },
  { id: 'afro4', title: 'Ojuelegba', artist: 'Wizkid', ytId: 'vJBhUL_y4P0', genre: 'afrobeats' },
  { id: 'afro5', title: 'Soco', artist: 'Wizkid', ytId: '8OJawBk5Kcc', genre: 'afrobeats' },
  { id: 'afro6', title: 'Mood', artist: 'Wizkid ft. Buju', ytId: 'FIxWN4kXjqE', genre: 'afrobeats' },
  { id: 'afro7', title: 'Fall', artist: 'Davido', ytId: 'HaNoxBcxv-w', genre: 'afrobeats' },
  { id: 'afro8', title: 'IF', artist: 'Davido', ytId: '79jIBN6rhXs', genre: 'afrobeats' },
  { id: 'afro9', title: 'Fem', artist: 'Davido', ytId: 'WMwjFbLQDqw', genre: 'afrobeats' },
  { id: 'afro10', title: 'Ye', artist: 'Burna Boy', ytId: 'YnXndxLSwFM', genre: 'afrobeats' },
  { id: 'afro11', title: 'On The Low', artist: 'Burna Boy', ytId: 'jpADhEcSYxU', genre: 'afrobeats' },
  { id: 'afro12', title: 'Last Last', artist: 'Burna Boy', ytId: 'uyUCqXq8cLU', genre: 'afrobeats' },
  { id: 'afro13', title: 'Anybody', artist: 'Burna Boy', ytId: 'D6N1R0eT9fg', genre: 'afrobeats' },
  { id: 'afro14', title: 'Kilometre', artist: 'Burna Boy', ytId: 'E7zCTjE62wI', genre: 'afrobeats' },
  { id: 'afro15', title: 'Gobe', artist: 'Burna Boy', ytId: 'C7kxG2SaFqw', genre: 'afrobeats' },
  { id: 'afro16', title: 'City Boys', artist: 'Burna Boy', ytId: 'yqH1EAb_G_A', genre: 'afrobeats' },
  { id: 'afro17', title: 'Water', artist: 'Tyla', ytId: 'ZRmg9R8qDmo', genre: 'afrobeats' },
  { id: 'afro18', title: 'Jump', artist: 'Tyla', ytId: 'iMKMFZkHvF0', genre: 'afrobeats' },
  { id: 'afro19', title: 'Calm Down', artist: 'Rema', ytId: 'CQLsdm1ZYAw', genre: 'afrobeats' },
  { id: 'afro20', title: 'Soundgasm', artist: 'Rema', ytId: 'Ff8kVN0FTkM', genre: 'afrobeats' },
  { id: 'afro21', title: 'Dumebi', artist: 'Rema', ytId: 'iDNYqwHB_nA', genre: 'afrobeats' },
  { id: 'afro22', title: 'Iron Man', artist: 'Rema', ytId: 'OAGmY9d5gvU', genre: 'afrobeats' },
  { id: 'afro23', title: 'Peru', artist: 'Fireboy DML', ytId: 'l3eSLha3ILQ', genre: 'afrobeats' },
  { id: 'afro24', title: 'Jealous', artist: 'Fireboy DML', ytId: '1oSx0ZLWsjQ', genre: 'afrobeats' },
  { id: 'afro25', title: 'Playboy', artist: 'Fireboy DML', ytId: 'F5r8C2dQ2Jk', genre: 'afrobeats' },
  { id: 'afro26', title: 'Love Nwantiti', artist: 'CKay', ytId: 'yvcoJfr95l8', genre: 'afrobeats' },
  { id: 'afro27', title: 'Emiliana', artist: 'CKay', ytId: 'i3JvTDlBf1s', genre: 'afrobeats' },
  { id: 'afro28', title: 'Monalisa', artist: 'Lojay & Sarz', ytId: 'F1mPvWSKoIQ', genre: 'afrobeats' },
  { id: 'afro29', title: 'Rush', artist: 'Ayra Starr', ytId: '6d6Lv0MJcq8', genre: 'afrobeats' },
  { id: 'afro30', title: 'Bloody Samaritan', artist: 'Ayra Starr', ytId: 'vXZp0Fh3lMI', genre: 'afrobeats' },
  { id: 'afro31', title: 'Sability', artist: 'Ayra Starr', ytId: 'fVqXDq-Yp1I', genre: 'afrobeats' },
  { id: 'afro32', title: 'Pana', artist: 'Tekno', ytId: 'LnA4Iu-9T9U', genre: 'afrobeats' },
  { id: 'afro33', title: 'Duro', artist: 'Tekno', ytId: 'PgDPF5OVOmA', genre: 'afrobeats' },
  { id: 'afro34', title: 'Johnny', artist: 'Yemi Alade', ytId: 'yqhc17cOTzE', genre: 'afrobeats' },
  { id: 'afro35', title: 'Onyeka', artist: 'Burna Boy', ytId: 'P4Ue2XJGrNE', genre: 'afrobeats' },
